CREATE TABLE lms_mentoring_feedback_control (
  id BIGINT PRIMARY KEY CHECK(id=1), activated_at BIGINT NOT NULL,
  _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE
);
CREATE TABLE lms_mentoring_feedback_requests (
  id TEXT PRIMARY KEY, booking_id TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('mentor','mentee')),
  discord_id TEXT NOT NULL, name TEXT NOT NULL, created_at BIGINT NOT NULL,
  UNIQUE(booking_id,role), _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE
);
CREATE TABLE lms_mentoring_feedback_responses (
  event_id TEXT PRIMARY KEY, request_id TEXT NOT NULL REFERENCES lms_mentoring_feedback_requests(id) DEFERRABLE INITIALLY DEFERRED,
  content TEXT NOT NULL, submitted_at BIGINT NOT NULL,
  _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE
);
CREATE INDEX lms_mentoring_feedback_response_request ON lms_mentoring_feedback_responses(request_id,submitted_at);
