CREATE TABLE mentors (
                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                discord_id  TEXT    NOT NULL UNIQUE,
                name        TEXT    NOT NULL,
                bio         TEXT    DEFAULT '',
                is_active   BIGINT NOT NULL DEFAULT 1
            , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE slots (
                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                mentor_id   BIGINT NOT NULL REFERENCES mentors(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
                start_time  TEXT    NOT NULL,
                end_time    TEXT    NOT NULL,
                label       TEXT    NOT NULL,
                is_active   BIGINT NOT NULL DEFAULT 1
            , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE bookings (
                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                slot_id     BIGINT NOT NULL UNIQUE REFERENCES slots(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
                user_id     TEXT    NOT NULL,
                user_name   TEXT    NOT NULL,
                booked_at   TEXT    NOT NULL DEFAULT (datetime('now'))
            , status TEXT NOT NULL DEFAULT 'approved', rejection_reason TEXT DEFAULT '', _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE panels (
                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                channel_id  TEXT    NOT NULL,
                message_id  TEXT    NOT NULL,
                guild_id    TEXT    NOT NULL
            , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE slot_templates (
                id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                mentor_id        BIGINT NOT NULL UNIQUE REFERENCES mentors(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
                start_hour       BIGINT NOT NULL DEFAULT 19,
                start_minute     BIGINT NOT NULL DEFAULT 0,
                end_hour         BIGINT NOT NULL DEFAULT 21,
                end_minute       BIGINT NOT NULL DEFAULT 0,
                interval_minutes BIGINT NOT NULL DEFAULT 30
            , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE blocked_dates (
                id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                mentor_id BIGINT NOT NULL REFERENCES mentors(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
                date      TEXT    NOT NULL,
                UNIQUE(mentor_id, date)
            , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE reminders (
                id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
                type       TEXT    NOT NULL,
                sent_at    TEXT    NOT NULL DEFAULT (datetime('now')),
                UNIQUE(booking_id, type)
            , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE qa_alerts (
                thread_id  TEXT PRIMARY KEY,
                alerted_at TEXT NOT NULL DEFAULT (datetime('now'))
            , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE blocked_weekdays (
                id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                mentor_id BIGINT NOT NULL REFERENCES mentors(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
                weekday   BIGINT NOT NULL,  -- 0=월 1=화 2=수 3=목 4=금 5=토 6=일
                UNIQUE(mentor_id, weekday)
            , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE onboarding_progress (
                user_id      TEXT PRIMARY KEY,
                guild_id     TEXT NOT NULL,
                joined_at    TEXT NOT NULL DEFAULT (datetime('now')),
                intro_done   BIGINT NOT NULL DEFAULT 0,
                completed_at TEXT
            , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE assignments (
                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                week        BIGINT NOT NULL,
                title       TEXT    NOT NULL,
                description TEXT    NOT NULL DEFAULT '',
                due_date    TEXT    NOT NULL,
                type        TEXT    NOT NULL DEFAULT 'team',
                created_at  TEXT    NOT NULL DEFAULT (datetime('now')),
                is_active   BIGINT NOT NULL DEFAULT 1
            , fields TEXT NOT NULL DEFAULT '["제출 내용"]', _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE submissions (
                id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                assignment_id BIGINT NOT NULL REFERENCES assignments(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
                user_id       TEXT    NOT NULL,
                user_name     TEXT    NOT NULL,
                team          TEXT    NOT NULL DEFAULT '',
                content       TEXT    NOT NULL,
                link          TEXT    NOT NULL DEFAULT '',
                submitted_at  TEXT    NOT NULL DEFAULT (datetime('now')),
                UNIQUE(assignment_id, user_id)
            , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE assignment_panels (
                panel_type  TEXT PRIMARY KEY,
                channel_id  TEXT NOT NULL,
                message_id  TEXT NOT NULL
            , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE assignment_reminders (
                assignment_id BIGINT NOT NULL,
                team          TEXT    NOT NULL,
                sent_at       TEXT    NOT NULL DEFAULT (datetime('now')),
                UNIQUE(assignment_id, team)
            , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE peer_eval_rounds (
                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title       TEXT    NOT NULL,
                created_at  TEXT    NOT NULL DEFAULT (datetime('now')),
                is_active   BIGINT NOT NULL DEFAULT 1
            , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE peer_evaluations (
                id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                round_id      BIGINT NOT NULL REFERENCES peer_eval_rounds(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
                team          TEXT    NOT NULL,
                evaluator_id  TEXT    NOT NULL,
                target_id     TEXT    NOT NULL,
                target_name   TEXT    NOT NULL,
                score1        BIGINT NOT NULL,  -- ① 과업 완수(산출물)
                score2        BIGINT NOT NULL,  -- ② 협업·소통
                score3        BIGINT NOT NULL,  -- ③ 책임·약속 이행
                score4        BIGINT NOT NULL,  -- ④ 팀 기여·문제해결
                comment       TEXT    NOT NULL DEFAULT '',
                submitted_at  TEXT    NOT NULL DEFAULT (datetime('now')),
                UNIQUE(round_id, evaluator_id, target_id)
            , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_records (kind TEXT NOT NULL, id TEXT NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)), PRIMARY KEY(kind,id), _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_audit (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor TEXT NOT NULL, action TEXT NOT NULL, target TEXT NOT NULL, before_json TEXT, after_json TEXT, created_at TEXT NOT NULL DEFAULT (datetime('now')), _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_assignment_courses (assignment_id BIGINT PRIMARY KEY REFERENCES assignments(id) DEFERRABLE INITIALLY IMMEDIATE, course_id TEXT NOT NULL, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_assignment_publications (assignment_id BIGINT PRIMARY KEY REFERENCES assignments(id) DEFERRABLE INITIALLY IMMEDIATE, created_at BIGINT NOT NULL, actor TEXT NOT NULL, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_booking_history (id TEXT PRIMARY KEY, data TEXT NOT NULL, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_attendance_rounds (course_id TEXT NOT NULL, date TEXT NOT NULL, period BIGINT NOT NULL, state TEXT NOT NULL CHECK(state IN ('진행 전','진행 중','마감')), version BIGINT NOT NULL, PRIMARY KEY(course_id,date,period), _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_attendance_requests (id TEXT PRIMARY KEY, actor TEXT NOT NULL, digest TEXT NOT NULL, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_attendance_codes (id TEXT PRIMARY KEY, code_hash TEXT NOT NULL UNIQUE, course_id TEXT NOT NULL, date TEXT NOT NULL, period BIGINT NOT NULL, guild_id TEXT NOT NULL, actor_id TEXT NOT NULL, student_ids TEXT NOT NULL CHECK(json_valid(student_ids)), created_at BIGINT NOT NULL, expires_at BIGINT NOT NULL, revoked_at BIGINT, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_outbox (
    id TEXT PRIMARY KEY,event_key TEXT NOT NULL UNIQUE,kind TEXT NOT NULL,source_id TEXT NOT NULL,
    guild_id TEXT NOT NULL DEFAULT '',channel_id TEXT NOT NULL DEFAULT '',payload TEXT NOT NULL,
    state TEXT NOT NULL DEFAULT 'pending',attempts BIGINT NOT NULL DEFAULT 0,
    claim TEXT,lease_until BIGINT,first_attempt_at BIGINT,message_id TEXT NOT NULL DEFAULT '',
    error TEXT NOT NULL DEFAULT '',actor TEXT NOT NULL,created_at BIGINT NOT NULL,completed_at BIGINT, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_outbox_attempts(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,outbox_id TEXT NOT NULL,state TEXT NOT NULL,error TEXT NOT NULL,created_at BIGINT NOT NULL, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_notification_control(id BIGINT PRIMARY KEY CHECK(id=1),importing BIGINT NOT NULL DEFAULT 0, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_submission_targets(submission_id BIGINT PRIMARY KEY REFERENCES submissions(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,target_key TEXT NOT NULL, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_remote_snapshots (source_id TEXT PRIMARY KEY, received_at TEXT NOT NULL, payload TEXT NOT NULL, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_users (
      id TEXT PRIMARY KEY, username TEXT NOT NULL UNIQUE, name TEXT NOT NULL,
      password_hash TEXT NOT NULL, discord_id TEXT NOT NULL UNIQUE, guild_id TEXT NOT NULL,
      created_at BIGINT NOT NULL
    , verified_at BIGINT, platform_role TEXT NOT NULL DEFAULT 'student' CHECK(platform_role IN ('admin','student')), must_change_password BIGINT NOT NULL DEFAULT 0, must_complete_profile BIGINT NOT NULL DEFAULT 0, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_registrations (
      ticket_hash TEXT PRIMARY KEY, code_hash TEXT NOT NULL UNIQUE, username TEXT NOT NULL,
      name TEXT NOT NULL, password_hash TEXT NOT NULL, discord_id TEXT NOT NULL, guild_id TEXT NOT NULL,
      created_at BIGINT NOT NULL, expires_at BIGINT NOT NULL, renewed_at BIGINT NOT NULL, verified_at BIGINT
    , user_id TEXT, workspace_id TEXT, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_auth_sessions (
      token_hash TEXT PRIMARY KEY, user_id TEXT REFERENCES lms_users(id) DEFERRABLE INITIALLY IMMEDIATE, admin_version TEXT,
      expires_at BIGINT NOT NULL
    , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_auth_limits (
      key_hash TEXT PRIMARY KEY, count BIGINT NOT NULL, expires_at BIGINT NOT NULL
    , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_account_audit (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor_id TEXT NOT NULL, target_id TEXT NOT NULL,
      username TEXT NOT NULL, action TEXT NOT NULL, created_at BIGINT NOT NULL
    , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_workspace_verifications (
    workspace_id TEXT NOT NULL, user_id TEXT NOT NULL, guild_id TEXT NOT NULL,
    discord_id TEXT NOT NULL, verified_at BIGINT NOT NULL,
    PRIMARY KEY(workspace_id,user_id,guild_id)
  , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_discord_plans (
      guild_id TEXT PRIMARY KEY, data TEXT NOT NULL CHECK(json_valid(data)), revision TEXT NOT NULL, updated_at BIGINT NOT NULL
    , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_discord_guilds (
      guild_id TEXT PRIMARY KEY, name TEXT NOT NULL, manage_channels BIGINT NOT NULL, seen_at BIGINT NOT NULL
    , member_count BIGINT, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_discord_jobs (
      id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, revision TEXT NOT NULL, plan TEXT NOT NULL CHECK(json_valid(plan)),
      state TEXT NOT NULL CHECK(state IN ('queued','running','succeeded','failed')),
      created_at BIGINT NOT NULL, completed_at BIGINT, lease_until BIGINT, claim_hash TEXT,
      error_code TEXT, results TEXT NOT NULL DEFAULT '[]'
    , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_discord_worker (id BIGINT PRIMARY KEY CHECK(id=1), bot_id TEXT NOT NULL, name TEXT NOT NULL, ready BIGINT NOT NULL, seen_at BIGINT NOT NULL, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_workspaces (
      id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL,
      source_id TEXT NOT NULL UNIQUE, created_at BIGINT NOT NULL
    , archived_at BIGINT, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_workspace_guilds (
      guild_id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES lms_workspaces(id) DEFERRABLE INITIALLY IMMEDIATE
    , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_workspace_members (
      workspace_id TEXT NOT NULL REFERENCES lms_workspaces(id) DEFERRABLE INITIALLY IMMEDIATE, user_id TEXT NOT NULL REFERENCES lms_users(id) DEFERRABLE INITIALLY IMMEDIATE,
      role TEXT NOT NULL CHECK(role IN ('admin','instructor','student')), joined_at BIGINT NOT NULL,
      PRIMARY KEY(workspace_id,user_id)
    , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_workspace_invitations (
      id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES lms_workspaces(id) DEFERRABLE INITIALLY IMMEDIATE, token_hash TEXT NOT NULL UNIQUE,
      username TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('admin','instructor','student')),
      created_by TEXT NOT NULL, created_at BIGINT NOT NULL, expires_at BIGINT NOT NULL, accepted_at BIGINT, revoked_at BIGINT
    , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_workspace_migrations (name TEXT PRIMARY KEY, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_mentor_scopes (workspace_id TEXT NOT NULL, subject_id TEXT NOT NULL, kind TEXT NOT NULL, team_ids TEXT NOT NULL, PRIMARY KEY(workspace_id,subject_id), _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_discord_templates (workspace_id TEXT PRIMARY KEY REFERENCES lms_workspaces(id) DEFERRABLE INITIALLY IMMEDIATE, data TEXT NOT NULL CHECK(json_valid(data)), revision TEXT NOT NULL, updated_at BIGINT NOT NULL, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_admissions (
    id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES lms_workspaces(id) DEFERRABLE INITIALLY IMMEDIATE, user_id TEXT NOT NULL REFERENCES lms_users(id) DEFERRABLE INITIALLY IMMEDIATE,
    state TEXT NOT NULL CHECK(state IN ('pending','approved','rejected','joined')), created_at BIGINT NOT NULL,
    reviewed_by TEXT, reviewed_at BIGINT, guild_id TEXT, reason TEXT NOT NULL DEFAULT '',
    invite_state TEXT NOT NULL DEFAULT 'none', invite_code TEXT, invite_expires BIGINT, claim_hash TEXT, lease_until BIGINT, purpose TEXT NOT NULL DEFAULT 'student', team_id TEXT NOT NULL DEFAULT '',
    UNIQUE(workspace_id,user_id)
  , _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_onboarding_settings(guild_id TEXT PRIMARY KEY REFERENCES lms_workspace_guilds(guild_id) DEFERRABLE INITIALLY IMMEDIATE, data TEXT NOT NULL, revision TEXT NOT NULL, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_onboarding_reports(guild_id TEXT PRIMARY KEY, revision TEXT NOT NULL, state TEXT NOT NULL, error TEXT NOT NULL, updated_at BIGINT NOT NULL, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_onboarding_members(guild_id TEXT NOT NULL, discord_id TEXT NOT NULL, intro_done BIGINT NOT NULL DEFAULT 0, updated_at BIGINT NOT NULL, PRIMARY KEY(guild_id,discord_id), _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_member_sync(guild_id TEXT NOT NULL,discord_id TEXT NOT NULL,revision TEXT NOT NULL,state TEXT NOT NULL,error TEXT NOT NULL,updated_at BIGINT NOT NULL,PRIMARY KEY(guild_id,discord_id), _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_member_retry(guild_id TEXT NOT NULL,discord_id TEXT NOT NULL,PRIMARY KEY(guild_id,discord_id), _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_staff_profiles (workspace_id TEXT NOT NULL, user_id TEXT NOT NULL, name TEXT NOT NULL, expertise TEXT NOT NULL, bio TEXT NOT NULL, steps TEXT NOT NULL DEFAULT '[]', updated_at BIGINT NOT NULL, PRIMARY KEY(workspace_id,user_id), _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_group_setup (workspace_id TEXT PRIMARY KEY, course_id TEXT NOT NULL, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_staff_connections (workspace_id TEXT NOT NULL, user_id TEXT NOT NULL, discord_id TEXT NOT NULL, PRIMARY KEY(workspace_id,user_id), _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_runtime_state(guild_id TEXT NOT NULL,kind TEXT NOT NULL,record_key TEXT NOT NULL,data TEXT NOT NULL,PRIMARY KEY(guild_id,kind,record_key), _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_storage_state(id BIGINT PRIMARY KEY CHECK(id=1),revision BIGINT NOT NULL DEFAULT 0, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_storage_receipts(id TEXT PRIMARY KEY,fingerprint TEXT NOT NULL,result TEXT NOT NULL, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_storage_imports(checksum TEXT PRIMARY KEY,guild_id TEXT NOT NULL,archive TEXT NOT NULL,state TEXT NOT NULL,error TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT(datetime('now')), _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE lms_bot_settings(guild_id TEXT PRIMARY KEY,data TEXT NOT NULL, _ax_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE UNIQUE INDEX lms_course_code ON lms_records(json_extract(data,'$.code'),json_extract(data,'$.cohort')) WHERE kind='courses';
CREATE UNIQUE INDEX lms_learner_discord ON lms_records(json_extract(data,'$.discordId')) WHERE kind='learners' AND json_extract(data,'$.discordId') <> '';
CREATE UNIQUE INDEX lms_team_code ON lms_records(json_extract(data,'$.courseId'),json_extract(data,'$.code')) WHERE kind='teams';
CREATE UNIQUE INDEX lms_attendance_unique ON lms_records(json_extract(data,'$.studentId'),json_extract(data,'$.courseId'),json_extract(data,'$.date'),json_extract(data,'$.period')) WHERE kind='attendance';
CREATE UNIQUE INDEX lms_score_unique ON lms_records(json_extract(data,'$.studentId'),json_extract(data,'$.courseId'),json_extract(data,'$.item')) WHERE kind='scores';
CREATE UNIQUE INDEX lms_learner_email ON lms_records(lower(json_extract(data,'$.email'))) WHERE kind='learners' AND json_extract(data,'$.email') <> '';
CREATE INDEX lms_sessions_expiry ON lms_auth_sessions(expires_at);
CREATE INDEX lms_registration_expiry ON lms_registrations(created_at);
CREATE UNIQUE INDEX lms_discord_active_job ON lms_discord_jobs(guild_id) WHERE state IN ('queued','running');
CREATE UNIQUE INDEX lms_workspace_single_guild ON lms_workspace_guilds(workspace_id);
