import { test, expect, type APIRequestContext } from '@playwright/test'
import { randomUUID } from 'node:crypto'


async function fixture(request: APIRequestContext, count: number) {
  const admin = await (await request.post('/api/login', { data: { password: 'test-only-password-1234' } })).json()
  const headers = { Authorization: `Bearer ${admin.token}` }
  const workspace = await (await request.post('/api/workspaces', { headers, data: { name: `출결 ${randomUUID()}` } })).json()
  const base = `/api/workspaces/${workspace.id}`
  const groups = await (await request.get(`${base}/discord/groups`, { headers })).json()
  const setup = await (await request.post(`${base}/discord/groups`, { headers, data: { count: 2, title: '출결 검증', revision: groups.revision } })).json()
  for (let offset = 0; offset < count; offset += 100) {
    const state = await (await request.get(`${base}/workspace`, { headers })).json()
    const changes = Array.from({ length: Math.min(100, count - offset) }, (_, i) => ({ kind: 'learners', value: { id: `s${offset + i}`, name: `학생${offset + i}`, email: '', discordId: '', courseId: setup.courseId, team: setup.teams[(offset + i) % 2].name, status: '정상', progress: 0, color: 'sage' } }))
    expect((await request.patch(`${base}/workspace`, { headers, data: { revision: state.revision, changes } })).status()).toBe(200)
  }
  const selected = { courseId: setup.courseId, date: '2026-09-18', period: 1 }
  const path = `${base}/attendance?${new URLSearchParams({ ...selected, period: '1' })}`
  return { headers, workspace, base, selected, path, setup }
}

async function start(request: APIRequestContext, f: Awaited<ReturnType<typeof fixture>>) {
  const roster = await (await request.get(f.path)).json()
  expect((await request.post(`${f.base}/attendance`, { data: { ...f.selected, revision: roster.revision, requestId: randomUUID(), action: 'start' } })).status()).toBe(200)
}

test('drafts survive guarded menu and round changes, with stable focus and individual undo', async ({ page }) => {
  const f = await fixture(page.request, 3)
  await start(page.request, f)
  await page.goto(`/?workspace=${f.workspace.id}#attendance`)
  await page.getByLabel('출결 날짜').fill(f.selected.date)
  await page.getByRole('button', { name: '확인 필요 3명' }).click()
  const student = page.getByRole('group', { name: '학생0 출결 상태', exact: true })
  await student.getByRole('button', { name: '출석', exact: true }).click()
  await expect(student.getByRole('button', { name: '출석', exact: true })).toBeFocused()
  await expect(page.locator('.attendance-roster tbody tr')).toHaveCount(3)
  await page.getByRole('button', { name: '학생0 입력 되돌리기' }).click()
  await expect(student.getByRole('button', { name: '출석', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await student.getByRole('button', { name: '출석', exact: true }).click()
  await page.getByLabel('등록·정정 사유').fill('현장 확인')
  const nav = page.getByRole('navigation', { name: '주 메뉴' })
  page.once('dialog', dialog => dialog.dismiss())
  await nav.getByRole('button', { name: '대시보드', exact: true }).click()
  await expect(page).toHaveURL(/#attendance$/)
  await expect(student).toBeVisible()
  page.once('dialog', dialog => dialog.dismiss())
  await page.evaluate(() => { location.hash = 'dashboard' })
  await expect(page).toHaveURL(/#attendance$/)
  page.once('dialog', dialog => dialog.accept())
  await nav.getByRole('button', { name: '대시보드', exact: true }).click()
  await expect(page.locator('.attendance-panel')).toHaveCount(0)
  await nav.getByRole('button', { name: '출결 관리', exact: true }).click()
  await expect(page.getByLabel('출결 날짜')).toHaveValue(f.selected.date)
  await expect(student.getByRole('button', { name: '출석', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByLabel('등록·정정 사유')).toHaveValue('현장 확인')
  await expect(page.getByRole('status')).toContainText('임시 보관한 입력을 복구')
  page.once('dialog', dialog => dialog.accept())
  await page.getByLabel('출결 날짜').fill('2026-09-19')
  await expect(page.locator('.attendance-summary')).toContainText('진행 전')
  await page.getByLabel('출결 날짜').fill(f.selected.date)
  await expect(student.getByRole('button', { name: '출석', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '출결 일괄 저장' }).click()
  await expect(page.getByRole('status')).toHaveText('명단 출결을 저장했습니다.')
  const roster = await (await page.request.get(f.path)).json()
  expect(roster.rows.find((row: { studentId: string }) => row.studentId === 's0')).toMatchObject({ status: '출석', reason: '현장 확인' })
  await page.getByRole('group', { name: '학생1 출결 상태', exact: true }).getByRole('button', { name: '출석', exact: true }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '로그아웃', exact: true }).click()
  await page.getByRole('button', { name: '관리자 로그인', exact: true }).click()
  await page.getByLabel('관리자 비밀번호').fill('test-only-password-1234')
  await page.getByRole('button', { name: '로그인', exact: true }).click()
  await page.getByRole('button', { name: '워크스페이스 선택', exact: true }).click()
  await page.getByLabel('워크스페이스 목록', { exact: true }).getByRole('button', { name: new RegExp(`^${f.workspace.name}`) }).click()
  await nav.getByRole('button', { name: '출결 관리', exact: true }).click()
  await page.getByLabel('출결 날짜').fill(f.selected.date)
  await expect(page.getByRole('group', { name: '학생1 출결 상태', exact: true }).getByRole('button', { name: '출석', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await expect(page.locator('.attendance-savebar')).toContainText('저장 전 변경 없음')
})

test('concurrent changes preserve drafts, require resolution for the same student, and show recoverable errors beside save', async ({ page }) => {
  const f = await fixture(page.request, 3)
  await start(page.request, f)
  const remoteSave = async (studentId: string, status: string) => {
    const roster = await (await page.request.get(f.path)).json()
    expect((await page.request.post(`${f.base}/attendance`, { data: { ...f.selected, revision: roster.revision, requestId: randomUUID(), action: 'save', entries: [{ studentId, status, reason: '다른 멘토 확인' }] } })).status()).toBe(200)
  }
  await page.goto(`/?workspace=${f.workspace.id}#attendance`)
  await page.getByLabel('출결 날짜').fill(f.selected.date)
  const state = (name: string, status: string) => page.getByRole('group', { name: `${name} 출결 상태`, exact: true }).getByRole('button', { name: status, exact: true })
  await state('학생0', '출석').click()
  await remoteSave('s1', '지각')
  await page.getByRole('button', { name: '출결 일괄 저장' }).click()
  await expect(page.getByRole('status')).toContainText('내 입력은 유지했습니다')
  await expect(state('학생0', '출석')).toHaveAttribute('aria-pressed', 'true')
  await expect(state('학생1', '지각')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('region', { name: '출결 충돌 해결' })).toHaveCount(0)
  await page.getByRole('button', { name: '출결 일괄 저장' }).click()
  await expect(page.getByRole('status')).toHaveText('명단 출결을 저장했습니다.')

  await state('학생0', '공결').click()
  await remoteSave('s0', '결석')
  await page.getByRole('button', { name: '출결 일괄 저장' }).click()
  const conflicts = page.getByRole('region', { name: '출결 충돌 해결' })
  await expect(conflicts).toContainText('최신: 결석 · 내 입력: 공결')
  await expect(page.getByRole('button', { name: '출결 일괄 저장' })).toBeDisabled()
  await page.getByRole('button', { name: '최신 기록 사용' }).click()
  await expect(state('학생0', '결석')).toHaveAttribute('aria-pressed', 'true')
  await state('학생0', '공결').click()
  await remoteSave('s0', '지각')
  await page.getByRole('button', { name: '명단 새로고침' }).click()
  await expect(conflicts).toContainText('최신: 지각 · 내 입력: 공결')
  await page.getByRole('button', { name: '내 입력 유지' }).click()
  await page.getByRole('button', { name: '출결 일괄 저장' }).click()
  await expect(page.getByRole('status')).toHaveText('명단 출결을 저장했습니다.')
  expect((await (await page.request.get(f.path)).json()).rows.find((row: { studentId: string }) => row.studentId === 's0').status).toBe('공결')

  await state('학생2', '출석').click()
  await page.route(`**${f.base}/attendance`, route => route.request().method() === 'POST' ? route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: '잠시 후 다시 시도하세요.' }) }) : route.continue())
  await page.getByRole('button', { name: '출결 일괄 저장' }).click()
  await expect(page.getByRole('alert')).toHaveText('잠시 후 다시 시도하세요.')
  await expect(page.getByRole('alert')).toBeInViewport()
  await expect(page.locator('.attendance-savebar')).toContainText('저장 전 변경 1명')
  await page.unroute(`**${f.base}/attendance`)
  await page.getByRole('button', { name: '출결 일괄 저장' }).click()
  await expect(page.getByRole('status')).toHaveText('명단 출결을 저장했습니다.')
})

test('compact roster supports pagination and bulk selection across matching pages', async ({ page }) => {
  const f = await fixture(page.request, 24)
  await start(page.request, f)
  await page.goto(`/?workspace=${f.workspace.id}#attendance`)
  await page.getByLabel('출결 날짜').fill(f.selected.date)
  await expect(page.locator('.attendance-roster tbody tr')).toHaveCount(10)
  await expect(page.getByRole('group', { name: '선택 학생 일괄 출결' })).toHaveCount(0)
  await page.getByLabel('출결 조 필터').selectOption(f.setup.teams[0].name)
  await page.getByLabel('검색 결과 전체 선택').check()
  await expect(page.locator('.attendance-bulk')).toContainText('선택한 12명')
  await page.getByRole('group', { name: '선택 학생 일괄 출결' }).getByRole('button', { name: '출석', exact: true }).click()
  await page.getByRole('button', { name: '전체 명단', exact: true }).click()
  await expect(page.getByLabel('출결 조 필터')).toHaveValue('')
  await page.getByRole('button', { name: '출결 일괄 저장' }).click()
  await expect(page.getByRole('status')).toHaveText('명단 출결을 저장했습니다.')
  expect((await (await page.request.get(f.path)).json()).counts).toMatchObject({ '출석': 12, '미처리': 12 })
  for (const [width, height] of [[1440, 900], [390, 844], [360, 800]]) {
    await page.setViewportSize({ width, height })
    await page.evaluate(() => window.scrollTo(0, 0))
    await expect(page.locator('.attendance-roster tbody tr')).toHaveCount(width < 640 ? 5 : 10)
    const layout = await page.locator('.attendance-roster').evaluate(element => ({ top: element.getBoundingClientRect().top + scrollY, overflow: getComputedStyle(element).overflowY, pageOverflow: document.documentElement.scrollWidth > innerWidth }))
    expect(layout.pageOverflow).toBe(false)
    expect(layout.top).toBeLessThan(width < 640 ? 900 : 800)
    if (width < 640) expect(layout.overflow).toBe('visible')
    await page.screenshot({ path: `test-results/attendance-editor-${width}.png`, fullPage: true })
  }
  await page.getByRole('button', { name: '다음 명단' }).click()
  await expect(page.getByRole('navigation', { name: '명단 페이지', exact: true })).toContainText('2 / 5쪽')
})

test('a failed initial roster load can be retried from the same screen', async ({ page }) => {
  const f = await fixture(page.request, 2)
  await start(page.request, f)
  let failing = true
  await page.route(/\/attendance\?/, route => failing ? route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: '명단 연결을 다시 확인하세요.' }) }) : route.continue())
  await page.goto(`/?workspace=${f.workspace.id}#attendance`)
  await page.getByLabel('출결 날짜').fill(f.selected.date)
  await expect(page.getByRole('alert')).toHaveText('명단 연결을 다시 확인하세요.')
  failing = false
  await page.getByRole('button', { name: '명단 새로고침' }).click()
  await expect(page.locator('.attendance-roster tbody tr')).toHaveCount(2)
  await expect(page.getByRole('alert')).toHaveCount(0)
})
