import { test, expect } from '@playwright/test'
import { randomUUID } from 'node:crypto'

test('mentor code UI accepts verified check-ins and preserves recorded evidence across code rotation and corrections', async ({ page }) => {
  const request = page.request, suffix = randomUUID().slice(0, 8)
  const guildId = '8' + Date.now().toString().padStart(17, '0'), discordId = '9' + Date.now().toString().padStart(17, '0')
  const legacy = await (await request.post('/api/login', { data: { password: 'test-only-password-1234' } })).json()
  const root = { Authorization: 'Bearer ' + legacy.token }
  const workspace = await (await request.post('/api/workspaces', { headers: root, data: { name: '코드 출석 ' + suffix, guildId } })).json()
  const base = '/api/workspaces/' + workspace.id
  const groups = await (await request.get(base + '/discord/groups', { headers: root })).json()
  const setup = await (await request.post(base + '/discord/groups', { headers: root, data: { count: 1, revision: groups.revision } })).json()
  const username = 'code.owner.' + suffix, password = 'attendance-password-12345'
  const invite = await (await request.post(base + '/invitations', { headers: root, data: { username, role: 'admin' } })).json()
  const ownerResponse = await request.post('/api/auth/register', { data: { invitationToken: invite.token, username, name: '코드 관리자', password } })
  expect(ownerResponse.status()).toBe(201)
  const owner = await ownerResponse.json(), headers = { Authorization: 'Bearer ' + owner.token }
  expect((await request.post('/api/invitations/accept', { headers, data: { token: invite.token } })).status()).toBe(200)
  const issuedResponse = await request.post(base + '/student-accounts', { headers, data: { username: 'code.student.' + suffix, teamId: setup.teams[0].id } })
  expect(issuedResponse.status()).toBe(201)
  const issued = await issuedResponse.json()
  const initial = await (await request.post('/api/auth/login', { data: { username: issued.username, password: issued.initialPassword } })).json()
  const studentResponse = await request.post('/api/auth/first-login', { headers: { Authorization: 'Bearer ' + initial.token }, data: { name: '코드 학생', currentPassword: issued.initialPassword, newPassword: 'student-new-password-12345' } })
  expect(studentResponse.status()).toBe(200)
  const student = await studentResponse.json(), studentHeaders = { Authorization: 'Bearer ' + student.token }
  const proofResponse = await request.post(base + '/me/verification', { headers: studentHeaders, data: {} })
  expect(proofResponse.status()).toBe(200)
  const proof = await proofResponse.json()
  const botHeaders = { Authorization: 'Bearer test-only-auth-token-12345678901234567890' }
  expect((await request.post('/api/integrations/discord/verify', { headers: botHeaders, data: { code: proof.code.replaceAll('-', ''), guildId, discordId } })).status()).toBe(200)
  expect((await request.get(base + '/attendance/code?courseId=' + setup.courseId + '&date=2026-09-18&period=1', { headers: studentHeaders })).status()).toBe(403)
  await request.post('/api/auth/login', { data: { username, password } })
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await page.goto('/?workspace=' + workspace.id + '#attendance')
  await page.getByLabel('강의 시작 예정 시각').fill('10:00')
  await page.getByLabel('강의 종료 예정 시각').fill('12:00')
  await page.getByRole('button', { name: '시작 코드 생성 · 강의 시작', exact: true }).click()
  const codeOutput = page.getByLabel('발급된 출석 코드')
  await expect(codeOutput).toHaveText(/^\d{6}$/)
  const code = (await codeOutput.textContent())!
  await page.locator('.attendance-code summary').click()
  await expect(codeOutput).toBeVisible()
  await page.locator('.attendance-code summary').click()
  await expect(codeOutput).toHaveText(code)
  const path = '/api/integrations/discord/attendance/checkin'
  const check = (value = code) => request.post(path, { headers: botHeaders, data: { guildId, discordId, code: value } })
  expect((await request.post(path, { headers: studentHeaders, data: { guildId, discordId, code } })).status()).toBe(401)
  const results = await Promise.all([check(), check()])
  expect(results.map(r => r.status())).toEqual([200, 200])
  const recorded = await Promise.all(results.map(r => r.json()))
  expect(recorded.map(r => r.alreadyRecorded).sort()).toEqual([false, true])
  await page.getByRole('button', {name:'명단 새로고침'}).click()
  await expect(page.locator('.attendance-summary')).toContainText('미처리 1명')
  await expect(codeOutput).toHaveText(code)
  await page.locator('.attendance-code summary').click()
  await expect(page.locator('.attendance-code-times')).toContainText('10:00–12:00')
  const reissued = page.waitForResponse(response => response.url().endsWith(base + '/attendance/code') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '시작 코드 재발급', exact: true }).click()
  expect((await reissued).ok()).toBeTruthy()
  await expect(codeOutput).toHaveText(/^\d{6}$/)
  await expect(codeOutput).not.toHaveText(code)
  // Retries return this verified student's committed evidence even after rotation.
  const retry = await check()
  expect(retry.status()).toBe(200)
  expect(await retry.json()).toMatchObject({ alreadyRecorded: true, checkInAt: recorded[0].checkInAt })
  const nextCode = (await codeOutput.textContent())!
  page.once('dialog', dialog => dialog.accept())
  const ended = page.waitForResponse(response => response.url().endsWith(base + '/attendance/code') && response.request().method() === 'POST')
  await page.locator('.attendance-code summary').click()
  await page.getByRole('button', {name:'종료 코드 생성 · 강의 종료'}).click()
  expect((await ended).ok()).toBeTruthy()
  await expect(codeOutput).toHaveText(/^\d{6}$/)
  await expect(codeOutput).not.toHaveText(nextCode)
  const endCode = (await codeOutput.textContent())!
  const endedRetry = await check(nextCode)
  expect(endedRetry.status()).toBe(200)
  expect(await endedRetry.json()).toMatchObject({ alreadyRecorded: true, checkInAt: recorded[0].checkInAt })
  await page.getByRole('group', { name: '코드 학생 출결 상태', exact: true }).getByRole('button', { name: '출석', exact: true }).click()
  await page.getByRole('button', { name: '출결 일괄 저장' }).click()
  await expect(page.locator('.attendance-feedback [role="status"]')).toHaveText('명단 출결을 저장했습니다.')
  await page.getByRole('button', { name: '확인 필요 1명' }).click()
  await expect(page.getByRole('region', { name: '출결 명단' })).toContainText('퇴실 미등록')
  expect((await check(endCode)).status()).toBe(200)
  await page.getByRole('button', {name:'명단 새로고침'}).click()
  await expect(page.getByRole('button', { name: '확인 필요 0명' })).toBeVisible()
  await page.getByRole('button', { name: '전체 명단', exact: true }).click()
  await expect(page.getByRole('group', { name: '코드 학생 출결 상태', exact: true }).getByRole('button', { name: '출석', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('group', { name: '코드 학생 출결 상태', exact: true }).getByRole('button', { name: '지각', exact: true }).click()
  await page.getByLabel('등록·정정 사유').fill('멘토가 실제 도착 시간 확인')
  await page.getByRole('button', { name: '출결 일괄 저장' }).click()
  await expect(page.locator('.attendance-feedback [role="status"]')).toHaveText('명단 출결을 저장했습니다.')
  expect((await (await check(endCode)).json()).status).toBe('지각')
  for (const width of [1440, 390, 360]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
    await page.evaluate(() => window.scrollTo(0, 0))
    await page.screenshot({ path: `test-results/attendance-code-${width}.png`, fullPage: true, animations: 'disabled' })
  }
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '출결 확정', exact: true }).click()
  await expect(page.locator('.attendance-feedback [role="status"]')).toHaveText('회차를 마감했습니다.')
  await expect(page.getByRole('region', { name: '강의 시작·종료 코드', exact: true })).toHaveCount(0)
  expect(errors).toEqual([])
})
