import { test, expect, type APIRequestContext } from '@playwright/test'
import { randomUUID } from 'node:crypto'
import { readFile } from 'node:fs/promises'

async function fixture(request: APIRequestContext, count: number) {
  const admin = await (await request.post('/api/login', { data: { password: 'test-only-password-1234' } })).json()
  const headers = { Authorization: `Bearer ${admin.token}` }
  const workspace = await (await request.post('/api/workspaces', { headers, data: { name: `출결 ${randomUUID()}` } })).json()
  const base = `/api/workspaces/${workspace.id}`
  const groups = await (await request.get(`${base}/discord/groups`, { headers })).json()
  const setup = await (await request.post(`${base}/discord/groups`, { headers, data: { count: 2, title: '출결 검증', revision: groups.revision } })).json()
  for (let offset = 0; offset < count; offset += 100) {
    const state = await (await request.get(`${base}/workspace`, { headers })).json()
    const changes = Array.from({ length: Math.min(100, count - offset) }, (_, i) => ({ kind: 'learners', value: { id: `s${offset + i}`, name: `학생${offset + i}`, email: '', discordId: '', courseId: setup.courseId, team: setup.teams[(offset + i) % 2].name, status: '정상', progress: 0, color: 'sage' } }))
    expect((await request.patch(`${base}/workspace`, { headers, data: { revision: state.revision, changes } })).status()).toBe(200)
  }
  const selected = { courseId: setup.courseId, date: '2026-09-18', period: 1 }
  const path = `${base}/attendance?${new URLSearchParams({ ...selected, period: '1' })}`
  return { headers, workspace, base, selected, path, setup }
}

test('120-person save, duplicate retry, simultaneous edits and group authorization use the real API', async ({ request }) => {
  const f = await fixture(request, 120)
  const get = async (headers = f.headers) => (await request.get(f.path, { headers })).json()
  const submit = (data: unknown, headers = f.headers) => request.post(`${f.base}/attendance`, { headers, data })
  let roster = await get()
  expect(roster.counts['미처리']).toBe(120)
  expect((await submit({ ...f.selected, requestId: randomUUID(), revision: roster.revision, action: 'start' })).status()).toBe(200)
  roster = await get()
  const body = { ...f.selected, requestId: randomUUID(), revision: roster.revision, action: 'save', entries: roster.rows.map((r: { studentId: string }) => ({ studentId: r.studentId, status: '출석' })) }
  expect((await submit(body)).status()).toBe(200)
  expect((await submit(body)).status()).toBe(200)
  roster = await get()
  expect(roster.counts['출석']).toBe(120)
  expect(roster.history).toHaveLength(120)
  const competing = await Promise.all(['지각', '결석'].map(status => submit({ ...body, requestId: randomUUID(), revision: roster.revision, entries: [{ studentId: 's0', status }] })))
  expect(competing.map(r => r.status()).sort()).toEqual([200, 409])
  const username = `mentor.${randomUUID().slice(0, 8)}`
  const invite = await (await request.post(`${f.base}/invitations`, { headers: f.headers, data: { username, role: 'instructor', mentorType: 'group', teamIds: [f.setup.teams[0].id] } })).json()
  const mentor = await (await request.post('/api/auth/register', { data: { invitationToken: invite.token, username, name: '담당 멘토', password: 'attendance-password-1234' } })).json()
  const mentorHeaders = { Authorization: `Bearer ${mentor.token}` }
  expect((await request.post('/api/invitations/accept', { headers: mentorHeaders, data: { token: invite.token } })).status()).toBe(200)
  const scoped = await get(mentorHeaders)
  expect(scoped.rows).toHaveLength(60)
  expect(scoped.rows.some((r: { studentId: string }) => r.studentId === 's1')).toBe(false)
  expect((await submit({ ...body, requestId: randomUUID(), revision: scoped.revision, entries: [{ studentId: 's1', status: '결석' }] }, mentorHeaders)).status()).toBe(403)
  expect((await submit({ ...f.selected, requestId: randomUUID(), revision: scoped.revision, action: 'close' }, mentorHeaders)).status()).toBe(403)
  expect((await request.get('/api/workspaces/default/attendance?courseId=foreign&date=2026-09-18&period=1', { headers: mentorHeaders })).status()).toBe(403)
  expect((await submit({ ...body, requestId: randomUUID(), revision: scoped.revision, entries: [{ studentId: 's0', status: '공결', reason: '담당 멘토 확인' }] }, mentorHeaders)).status()).toBe(200)
})

test('roster UI supports exceptions, CSV recovery, finalization, correction history and mobile layouts', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  const f = await fixture(page.request, 3)
  await page.goto(`/?workspace=${f.workspace.id}#attendance`)
  await page.getByLabel('출결 날짜').fill(f.selected.date)
  await expect(page.locator('.attendance-summary')).toContainText('미처리 3명')
  const beforeStart = await (await page.request.get(`/api/workspaces/${f.workspace.id}/attendance?` + new URLSearchParams({...f.selected, period: String(f.selected.period)}))).json()
  expect((await page.request.post(`/api/workspaces/${f.workspace.id}/attendance`, {data: {...f.selected, action: 'start', revision: beforeStart.revision, requestId: randomUUID()}})).status()).toBe(200)
  await page.getByRole('button', {name: '명단 새로고침'}).click()
  await expect(page.locator('.attendance-summary')).toContainText('진행 중')
  await page.getByRole('button', { name: '미처리 3명 출석' }).click()
  await page.getByRole('group', { name: '학생1 출결 상태', exact: true }).getByRole('button', { name: '지각', exact: true }).click()
  await page.getByRole('button', { name: '출결 일괄 저장' }).click()
  await expect(page.getByRole('status')).toHaveText('명단 출결을 저장했습니다.')
  await expect(page.getByRole('button', { name: '출결 확정' })).toBeEnabled()
  await page.getByText('CSV 내보내기 · 복구 입력', { exact: true }).click()
  const downloading = page.waitForEvent('download')
  await page.getByRole('button', { name: '출결 CSV 내보내기' }).click()
  const download = await downloading, csv = await readFile((await download.path())!, 'utf8')
  expect(csv).toContain('studentId')
  await page.getByLabel('출결 CSV 가져오기').setInputFiles({ name: 'recovery.csv', mimeType: 'text/csv', buffer: Buffer.from(csv.replace('"지각"', '"공결"')) })
  await expect(page.getByRole('status')).toContainText('CSV를 불러왔습니다.')
  await expect(page.getByRole('group', { name: '학생1 출결 상태', exact: true }).getByRole('button', { name: '공결', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '출결 일괄 저장' }).click()
  await expect(page.getByRole('status')).toHaveText('명단 출결을 저장했습니다.')
  await expect(page.getByRole('button', { name: '출결 확정' })).toBeEnabled()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '출결 확정' }).click()
  await expect(page.getByRole('status')).toHaveText('회차를 마감했습니다.')
  await page.getByRole('group', { name: '학생0 출결 상태', exact: true }).getByRole('button', { name: '지각', exact: true }).click()
  await page.getByRole('button', { name: '출결 일괄 저장' }).click()
  await expect(page.getByRole('alert')).toHaveText('마감 후 정정 사유를 입력하세요.')
  await page.getByLabel('등록·정정 사유').fill('수기 명단과 대조')
  await page.getByRole('button', { name: '출결 일괄 저장' }).click()
  await expect(page.getByRole('status')).toHaveText('명단 출결을 저장했습니다.')
  await page.reload()
  await page.getByLabel('출결 날짜').fill(f.selected.date)
  await expect(page.getByRole('group', { name: '학생0 출결 상태', exact: true }).getByRole('button', { name: '지각', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByText('출결 변경 이력 · 최근 200건').click()
  await expect(page.locator('.attendance-audit')).toContainText('수기 명단과 대조')
  for (const width of [1440, 390, 360]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
    await page.screenshot({ path: `test-results/attendance-${width}.png`, fullPage: true, animations: 'disabled' })
  }
  expect(errors).toEqual([])
})

test('filtered selection updates only selected learners and pending shortcut preserves exceptions', async ({ page }) => {
  const f = await fixture(page.request, 6)
  await page.goto(`/?workspace=${f.workspace.id}#attendance`)
  await page.getByLabel('출결 날짜').fill(f.selected.date)
  const beforeStart = await (await page.request.get(`/api/workspaces/${f.workspace.id}/attendance?` + new URLSearchParams({...f.selected, period: String(f.selected.period)}))).json()
  expect((await page.request.post(`/api/workspaces/${f.workspace.id}/attendance`, {data: {...f.selected, action: 'start', revision: beforeStart.revision, requestId: randomUUID()}})).status()).toBe(200)
  await page.getByRole('button', {name: '명단 새로고침'}).click()
  await expect(page.locator('.attendance-summary')).toContainText('진행 중')
  await page.getByLabel('출결 조 필터').selectOption(f.setup.teams[0].name)
  await page.getByLabel('표시된 수강생 전체 선택').check()
  await page.getByRole('group', { name: '선택 학생 일괄 출결' }).getByRole('button', { name: '출석', exact: true }).click()
  await page.getByLabel('출결 조 필터').selectOption('')
  const state = (name: string, status: string) => page.getByRole('group', { name: `${name} 출결 상태`, exact: true }).getByRole('button', { name: status, exact: true })
  await expect(state('학생0', '출석')).toHaveAttribute('aria-pressed', 'true')
  await expect(state('학생1', '출석')).toHaveAttribute('aria-pressed', 'false')
  await state('학생1', '지각').click()
  await page.getByRole('button', { name: '미처리 2명 출석' }).click()
  await expect(state('학생1', '지각')).toHaveAttribute('aria-pressed', 'true')
  await page.getByLabel('학생2 선택').check()
  await page.getByLabel('수강생 검색').fill('학생3')
  await expect(page.getByRole('group', { name: '선택 학생 일괄 출결' }).getByRole('button', { name: '결석', exact: true })).toBeDisabled()
  await page.getByLabel('학생3 선택').check()
  await page.getByRole('group', { name: '선택 학생 일괄 출결' }).getByRole('button', { name: '결석', exact: true }).click()
  await page.getByRole('button', { name: '출결 일괄 저장' }).click()
  await expect(page.getByRole('status')).toHaveText('명단 출결을 저장했습니다.')
  const roster = await (await page.request.get(f.path)).json()
  expect(roster.counts).toMatchObject({ '출석': 4, '지각': 1, '결석': 1, '미처리': 0 })
  await page.getByText('Discord 출결 집계 공유', { exact: true }).click()
  await expect(page.locator('.attendance-discord')).toContainText('Discord 서버를 연결하세요.')
  await expect(page.getByRole('button', { name: 'Discord에 출결 집계 공유' })).toBeDisabled()
})

test('review queue batches missing attendance within the visible team and explains finalization blockers', async ({ page }) => {
  const f = await fixture(page.request, 6)
  let roster = await (await page.request.get(f.path)).json()
  roster = await (await page.request.post(`${f.base}/attendance`, { data: { ...f.selected, revision: roster.revision, requestId: randomUUID(), action: 'start' } })).json()
  expect((await page.request.post(`${f.base}/attendance`, { data: { ...f.selected, revision: roster.revision, requestId: randomUUID(), action: 'save', entries: [{ studentId: 's0', status: '지각' }, { studentId: 's1', status: '출석' }] } })).status()).toBe(200)
  await page.goto(`/?workspace=${f.workspace.id}#attendance`)
  await page.getByLabel('출결 날짜').fill(f.selected.date)
  await expect(page.locator('#attendance-close-hint')).toHaveText('미처리 4명의 출결을 입력하세요.')
  await expect(page.getByRole('button', { name: '출결 확정', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '확인 필요 4명' }).click()
  await page.getByLabel('출결 조 필터').selectOption(f.setup.teams[0].name)
  await expect(page.locator('.attendance-roster tbody tr')).toHaveCount(2)
  await page.getByRole('button', { name: '미처리 2명 결석' }).click()
  await expect(page.locator('.attendance-roster tbody tr')).toHaveCount(0)
  await expect(page.locator('#attendance-close-hint')).toHaveText('변경한 2명의 출결을 먼저 저장하세요.')
  expect((await (await page.request.get(f.path)).json()).counts['결석']).toBe(0)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '입력 되돌리기' }).click()
  await expect(page.locator('.attendance-roster tbody tr')).toHaveCount(2)
  await page.getByRole('button', { name: '미처리 2명 결석' }).click()
  await page.getByRole('button', { name: '출결 일괄 저장' }).click()
  await expect(page.getByRole('status')).toHaveText('명단 출결을 저장했습니다.')
  roster = await (await page.request.get(f.path)).json()
  expect(roster.counts).toMatchObject({ '미처리': 2, '결석': 2, '지각': 1, '출석': 1 })
  expect(roster.rows.filter((row: { status: string }) => row.status === '결석').map((row: { studentId: string }) => row.studentId).sort()).toEqual(['s2', 's4'])
  await expect(page.locator('#attendance-close-hint')).toHaveText('미처리 2명의 출결을 입력하세요.')
  await page.getByRole('button', { name: '필터 초기화' }).click()
  await expect(page.locator('.attendance-roster tbody tr')).toHaveCount(6)
  await page.getByRole('button', { name: '미처리 2명 결석' }).click()
  await page.getByRole('button', { name: '출결 일괄 저장' }).click()
  await expect(page.getByRole('button', { name: '출결 확정', exact: true })).toBeEnabled()
  await page.setViewportSize({ width: 360, height: 800 })
  const list = page.getByRole('region', { name: '출결 명단', exact: true })
  expect(await list.evaluate(element => element.scrollHeight > element.clientHeight && element.clientHeight <= 560)).toBeTruthy()
  await list.scrollIntoViewIfNeeded()
  await list.evaluate(element => { element.scrollTop = element.scrollHeight })
  await expect(page.getByRole('group', { name: '학생5 출결 상태', exact: true })).toBeInViewport()
})
