import { test, expect } from '@playwright/test'

test('selected applicants are grouped and approved; stale selections are reported and mobile controls fit', async ({ page, request }) => {
  const login = await (await request.post('/api/login', { data: { password: 'test-only-password-1234' } })).json()
  const headers = { Authorization: `Bearer ${login.token}` }, guildId = '783456789012345611'
  const created = await request.post('/api/workspaces', { headers, data: { name: '일괄 승인 수업', guildId } })
  expect(created.status()).toBe(201)
  const workspace = await created.json(), base = `/api/workspaces/${workspace.id}`
  const data = await (await request.get(`${base}/workspace`, { headers })).json()
  const groups = await (await request.post(`${base}/discord/groups`, { headers, data: { count: 2, revision: data.revision } })).json()
  for (let i = 1; i <= 5; i++) expect((await request.post('/api/auth/student/register', { data: { workspaceId: workspace.id, username: `bulk.ui.student${i}`, name: i <= 2 ? `묶음 학생 ${i}` : `개별 학생 ${i}`, password: 'bulk-test-password-1234' } })).status()).toBe(201)
  const applications = (await (await request.get(`${base}/admissions`, { headers })).json()).applications
  const applicant = (i: number) => applications.find((a: { username: string }) => a.username === `bulk.ui.student${i}`)
  await page.goto(`/?workspace=${workspace.id}#learners`)
  await page.getByRole('button', { name: '관리자 로그인', exact: true }).click()
  await page.getByLabel('관리자 비밀번호').fill('test-only-password-1234')
  await page.getByRole('button', { name: '로그인', exact: true }).click()
  const review = page.getByRole('region', { name: '수강생 가입 승인', exact: true })
  await expect(review.getByRole('heading', { name: '묶음 학생 1', exact: true })).toBeVisible()
  await review.getByLabel('가입 신청자 검색').fill('묶음')
  await review.getByRole('checkbox', { name: '현재 목록 전체 선택' }).check()
  await expect(review.getByRole('button', { name: '선택 2명 승인 · 조 배정', exact: true })).toBeDisabled()
  await review.getByLabel('일괄 배정할 조').selectOption(groups.teams[0].id)
  await review.getByLabel('가입 신청자 검색').fill('개별')
  await expect(review.getByText('3명 표시 · 목록 밖 2명 선택됨')).toBeVisible()
  await review.getByLabel('가입 신청자 검색').fill('')
  for (const width of [1440, 390, 360]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `test-results/bulk-admissions-${width}.png`, fullPage: true, animations: 'disabled' })
  }
  await review.getByRole('button', { name: '선택 2명 승인 · 조 배정', exact: true }).click()
  await expect(review.getByRole('status')).toContainText('2명 승인·조 배정 완료')
  await expect(review.getByRole('heading', { name: '묶음 학생 1', exact: true })).toHaveCount(0)
  let roster = await (await request.get(`${base}/workspace`, { headers })).json()
  expect(roster.learners).toHaveLength(2)
  expect(roster.learners.every((l: { team: string }) => l.team === '1조')).toBe(true)
  await review.getByRole('checkbox', { name: '개별 학생 3 (bulk.ui.student3) 선택' }).check()
  await expect(review.getByRole('checkbox', { name: '현재 목록 전체 선택' })).toHaveJSProperty('indeterminate', true)
  await review.getByRole('checkbox', { name: '개별 학생 4 (bulk.ui.student4) 선택' }).check()
  await review.getByLabel('일괄 배정할 조').selectOption(groups.teams[1].id)
  expect((await request.post(`${base}/admissions/${applicant(3).id}/review`, { headers, data: { action: 'approve', guildId, teamId: groups.teams[0].id } })).status()).toBe(200)
  await review.getByRole('button', { name: '선택 2명 승인 · 조 배정', exact: true }).click()
  await expect(review.getByRole('status')).toContainText('1명 승인·조 배정 완료 · 1명 처리하지 못함')
  await expect(review.getByRole('alert')).toContainText('개별 학생 3 · 이미 처리한 신청입니다.')
  roster = await (await request.get(`${base}/workspace`, { headers })).json()
  expect(roster.learners).toHaveLength(4)
  expect(roster.learners.find((l: { name: string }) => l.name === '개별 학생 3').team).toBe('1조')
  expect(roster.learners.find((l: { name: string }) => l.name === '개별 학생 4').team).toBe('2조')
  await review.getByRole('button', { name: '개별 학생 5 개별 처리', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '개별 학생 5 · 개별 처리' })
  await dialog.getByLabel('처리 사유').fill('과정 확인 필요')
  await dialog.getByRole('button', { name: '반려', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(review.getByText('가입 신청이 없습니다.', { exact: true })).toBeVisible()
  expect((await (await request.get(`${base}/admissions`, { headers })).json()).applications.find((a: { id: string }) => a.id === applicant(5).id).state).toBe('rejected')
})
