import { test, expect } from '@playwright/test'

test('course starts despite external assignment writes and weekly schedules persist, validate and preserve conflicting drafts', async ({ page }) => {
  await page.request.post('/api/login', { data: { password: 'test-only-password-1234' } })
  const w = await (await page.request.post('/api/workspaces', { data: { name: '과정 일정 검증' } })).json(), base = `/api/workspaces/${w.id}`
  const course = { id: 'schedule-course', title: '주차별 실습 과정', category: 'AX', description: 'AI 프로젝트 실습', progress: 0, learners: 0, weeks: '4주', mentor: '', theme: 'green', status: '모집 중', code: 'WEEKLY', cohort: '1기', startDate: '2026-09-01', endDate: '2026-09-30' }
  const state = await (await page.request.get(`${base}/workspace`)).json()
  expect((await page.request.patch(`${base}/workspace`, { data: { revision: state.revision, changes: [{ kind: 'courses', value: course }] } })).ok()).toBe(true)
  await page.goto(`/?workspace=${w.id}#courses`)
  await page.getByRole('button', { name: /주차별 실습 과정/ }).click()
  const modal = page.getByRole('dialog', { name: course.title })
  await expect(modal.getByRole('button', { name: '운영 시작', exact: true })).toBeEnabled()
  const current = await (await page.request.get(`${base}/workspace`)).json()
  expect((await page.request.patch(`${base}/workspace`, { data: { revision: current.revision, changes: [{ kind: 'assignments', value: { id: 'new-assignment', title: '미리 만든 과제', courseId: course.id, course: course.title, due: '2026-09-20', submitted: 0, total: 0, status: '진행 중' } }] } })).ok()).toBe(true)
  await modal.getByRole('button', { name: '운영 시작', exact: true }).click()
  await expect(modal.getByRole('button', { name: '과정 종료', exact: true })).toBeEnabled()
  await expect(modal).toContainText('미리 만든 과제')
  await modal.getByRole('button', { name: '주차별 일정', exact: true }).click()
  await modal.getByRole('button', { name: '주차 일정 자동 채우기' }).click()
  const rows = modal.locator('.course-session-editor')
  await expect(rows).toHaveCount(4)
  await rows.first().getByLabel('수업명', { exact: true }).fill('AI 도구 실습')
  await rows.first().getByLabel('시작 시간').fill('10:00')
  await rows.first().getByLabel('종료 시간').fill('12:00')
  await rows.first().getByLabel('메모').fill('노트북 지참')
  await modal.getByRole('button', { name: '일정 저장', exact: true }).click()
  await expect(modal.getByRole('status')).toContainText('주차별 일정을 저장했습니다.')
  await modal.getByRole('button', { name: '닫기', exact: true }).click()
  await page.reload()
  await page.getByRole('button', { name: /주차별 실습 과정/ }).click()
  await modal.getByRole('button', { name: '주차별 일정', exact: true }).click()
  await expect(rows).toHaveCount(4)
  await expect(rows.first().getByLabel('수업명', { exact: true })).toHaveValue('AI 도구 실습')
  await rows.first().getByLabel('메모').fill('내 편집 내용')
  const latest = await (await page.request.get(`${base}/courses/${course.id}/manage`)).json()
  expect((await page.request.patch(`${base}/courses/${course.id}/manage`, { data: { revision: latest.revision, changes: { status: '종료' } } })).ok()).toBe(true)
  await modal.getByRole('button', { name: '일정 저장', exact: true }).click()
  await expect(modal.getByRole('alert')).toContainText('다른 관리자가 이 과정을 수정했습니다.')
  await expect(rows.first().getByLabel('메모')).toHaveValue('내 편집 내용')
  await modal.getByRole('button', { name: '입력 취소하고 최신 과정 불러오기' }).click()
  await expect(rows.first().getByLabel('메모')).toHaveValue('노트북 지참')
  await modal.getByRole('button', { name: '수업 4 삭제' }).click()
  await modal.getByRole('button', { name: '일정 저장', exact: true }).click()
  await expect(modal.getByRole('status')).toContainText('주차별 일정을 저장했습니다.')
  expect((await (await page.request.get(`${base}/courses/${course.id}/manage`)).json()).course.schedule).toHaveLength(3)
  for (const width of [1440, 390, 360]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await modal.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
    await page.screenshot({ path: `test-results/course-management-${width}.png`, animations: 'disabled' })
  }
  await rows.first().getByLabel('수업명', { exact: true }).fill('저장하지 않을 수업명')
  await modal.getByRole('button', { name: '닫기', exact: true }).click()
  await expect(modal.getByRole('button', { name: '계속 편집' })).toBeVisible()
  await modal.getByRole('button', { name: '변경 취소하고 닫기' }).click()
  await expect(modal).not.toBeVisible()
})
