import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('only platform admins can download, validate, reset and restore all service data', async ({ page, request }, testInfo) => {
  test.setTimeout(120000)
  const site = 'http://localhost:3006', api = site + '/api'
  expect((await request.get(api + '/admin/data')).status()).toBe(401)
  const preflight = await request.fetch(api + '/admin/data/preview', { method: 'OPTIONS', headers: { Origin: site, 'Access-Control-Request-Method': 'POST', 'Access-Control-Request-Headers': 'Content-Type,Authorization' } })
  expect(preflight.status()).toBe(204)
  expect(preflight.headers()['access-control-allow-origin']).toBe(site)
  expect((await request.post(api + '/admin/data/preview', { data: { backup: 'bad' } })).status()).toBe(401)
  const setup = await request.post(api + '/auth/setup', { data: { username: 'data.owner', name: '총관리자', password: 'owner-password-1234', setupKey: 'data-setup-key-123456' } })
  expect(setup.status()).toBe(201)
  const owner = await setup.json(), headers = { Authorization: `Bearer ${owner.token}` }
  const created = await (await request.post(api + '/workspaces', { headers, data: { name: '백업할 운영 과정' } })).json()
  const base = api + '/workspaces/' + created.id
  const issued = await (await request.post(base + '/invitations/account', { headers, data: { username: 'data.staff', name: '운영자' } })).json()
  const initial = await (await request.post(api + '/auth/login', { data: { username: 'data.staff', password: issued.initialPassword } })).json()
  const changed = await (await request.post(api + '/auth/password', { headers: { Authorization: 'Bearer ' + initial.token }, data: { currentPassword: issued.initialPassword, newPassword: 'staff-password-1234' } })).json()
  const staffHeaders = { Authorization: 'Bearer ' + changed.token }
  expect((await request.post(api + '/invitations/accept', { headers: staffHeaders, data: { token: issued.token } })).status()).toBe(200)
  for (const path of ['/admin/data', '/admin/data/backup', '/admin/data/backups/missing']) expect((await request.get(api + path, { headers: staffHeaders })).status()).toBe(403)
  for (const path of ['/admin/data/reset', '/admin/data/restore', '/admin/data/preview']) expect((await request.post(api + path, { headers: staffHeaders, data: {} })).status()).toBe(403)
  expect((await request.post(api + '/admin/data/reset', { headers, data: { confirmation: 'wrong', currentPassword: 'owner-password-1234' } })).status()).toBe(422)
  expect((await request.post(api + '/admin/data/reset', { headers, data: { confirmation: '전체 데이터 초기화', currentPassword: 'incorrect' } })).status()).toBe(401)
  expect((await request.get(api + '/admin/data/backup', { headers: { ...headers, Origin: 'https://untrusted.example' } })).status()).toBe(403)

  await page.goto(site + '/?workspace=' + created.id + '#data-admin')
  await page.getByLabel('아이디', { exact: true }).fill('data.owner')
  await page.getByLabel('비밀번호', { exact: true }).fill('owner-password-1234')
  await page.locator('button[type=submit]').click()
  await expect(page.getByRole('heading', { name: '백업 · 데이터 관리', exact: true })).toBeVisible()
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '전체 백업 다운로드', exact: true }).click()
  const download = await downloadEvent
  expect(download.suggestedFilename()).toMatch(/\.axbackup$/)
  const path = testInfo.outputPath('roundtrip.axbackup')
  await download.saveAs(path)
  const bytes = await readFile(path)
  await page.getByLabel('복구할 백업 파일').setInputFiles({ name: 'broken.axbackup', mimeType: 'application/octet-stream', buffer: Buffer.from('broken') })
  await page.getByRole('button', { name: '백업 파일 검증', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('백업 파일')
  await page.getByLabel('복구할 백업 파일').setInputFiles(path)
  await page.getByRole('button', { name: '백업 파일 검증', exact: true }).click()
  await expect(page.getByText('복구 파일 검증 완료', { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('data-admin-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(() => page.locator('.sidebar').evaluate(node => node.getBoundingClientRect().right)).toBeLessThanOrEqual(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('data-admin-mobile.png'), fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: '전체 데이터 초기화', exact: true }).click()
  const reset = page.getByRole('dialog', { name: '전체 데이터 초기화 확인' })
  await expect(reset.getByRole('button', { name: '초기화 실행' })).toBeDisabled()
  await reset.getByLabel('현재 총관리자 비밀번호').fill('owner-password-1234')
  await reset.getByLabel('확인 문구: 전체 데이터 초기화').fill('전체 데이터 초기화')
  await reset.getByRole('button', { name: '초기화 실행' }).click()
  await expect(page.getByRole('heading', { name: '데이터 초기화 완료' })).toBeVisible()
  expect((await request.get(api + '/auth/me', { headers })).status()).toBe(401)
  expect((await (await request.get(api + '/auth/config')).json()).setupEnabled).toBe(true)
  await page.getByRole('button', { name: '로그인 화면으로 이동' }).click()
  await page.getByRole('button', { name: '최초 관리자 등록', exact: true }).click()
  await page.getByLabel('이름', { exact: true }).fill('복구 담당자')
  await page.getByLabel('아이디', { exact: true }).fill('restore.owner')
  await page.getByLabel('비밀번호', { exact: true }).fill('restore-password-1234')
  await page.getByLabel('비밀번호 확인', { exact: true }).fill('restore-password-1234')
  await page.getByLabel('관리자 설정 키', { exact: true }).fill('data-setup-key-123456')
  await page.getByRole('button', { name: '관리자 계정 만들기' }).click()
  await expect(page.getByRole('heading', { name: '운영 대시보드', exact: true })).toBeVisible()
  await page.goto(site + '/#data-admin')
  await expect(page.getByRole('heading', { name: '백업 · 데이터 관리', exact: true })).toBeVisible()
  await expect(page.locator('.data-backup-list li')).toHaveCount(1)
  await page.getByLabel('복구할 백업 파일').setInputFiles({ name: 'roundtrip.axbackup', mimeType: 'application/octet-stream', buffer: bytes })
  await page.getByRole('button', { name: '백업 파일 검증', exact: true }).click()
  await page.getByRole('button', { name: '이 백업으로 복구' }).click()
  const restore = page.getByRole('dialog', { name: '백업 복구 확인' })
  await restore.getByLabel('현재 총관리자 비밀번호').fill('restore-password-1234')
  await restore.getByLabel('확인 문구: 백업으로 전체 복구').fill('백업으로 전체 복구')
  await restore.getByRole('button', { name: '복구 실행' }).click()
  await expect(page.getByRole('heading', { name: '백업 복구 완료' })).toBeVisible()
  const login = await request.post(api + '/auth/login', { data: { username: 'data.owner', password: 'owner-password-1234' } })
  expect(login.status()).toBe(200)
  const restoredHeaders = { Authorization: 'Bearer ' + (await login.json()).token }
  const workspaces = await (await request.get(api + '/workspaces', { headers: restoredHeaders })).json()
  expect(workspaces.workspaces.some((w: { id: string }) => w.id === created.id)).toBe(true)
  const status = await (await request.get(api + '/admin/data', { headers: restoredHeaders })).json()
  expect(status.backups).toHaveLength(2)
  expect((await request.get(api + '/admin/data/backups/' + status.backups[0].id, { headers: restoredHeaders })).status()).toBe(200)
})
