import { test, expect } from '@playwright/test'

test('deliver a new administrator account, change the initial password, and accept only its workspace', async ({ page, request, context }) => {
  await page.request.post('/api/login', { data: { password: 'test-only-password-1234' } })
  await page.goto('/?workspace=default#members')
  await page.getByLabel('초대할 아이디').fill('delivery.owner')
  await page.getByLabel('참여 권한').selectOption('admin')
  await page.getByLabel('관리자 이름').fill('초대받은 관리자')
  await page.getByRole('button', { name: '계정과 초대 링크 만들기', exact: true }).click()
  const message = page.getByLabel('전달할 초대 안내문')
  await expect(message).toHaveValue(/초기 비밀번호: /)
  const delivery = await message.inputValue()
  const link = await page.getByLabel('초대 링크', { exact: true }).inputValue()
  const initialPassword = delivery.match(/초기 비밀번호: (\S+)/)![1]
  const token = new URL(link).hash.slice(8)
  expect(delivery).toContain('아이디: delivery.owner')
  expect(delivery).toContain('워크스페이스 관리자')
  expect(delivery).toContain('초대 만료:')
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.getByRole('button', { name: '초대 안내문 복사' }).click()
  await expect(page.getByRole('status')).toContainText('복사했습니다.')
  expect((await page.evaluate(() => navigator.clipboard.readText())).replaceAll('\r\n', '\n')).toBe(delivery)
  for (const width of [390, 1440]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  }
  const saved = await (await page.request.get('/api/workspaces/default/members')).text()
  expect(saved).not.toContain(initialPassword)
  const storage = await page.evaluate(() => JSON.stringify({ ...localStorage, ...sessionStorage }))
  expect(storage).not.toContain(initialPassword)
  await page.reload()
  await expect(message).toHaveCount(0)
  await page.request.post('/api/logout', { data: {} })
  await page.goto(link)
  await expect(page.getByRole('button', { name: '회원가입', exact: true })).toHaveCount(0)
  await page.getByLabel('아이디', { exact: true }).fill('delivery.owner')
  await page.getByLabel('비밀번호', { exact: true }).fill(initialPassword)
  await page.locator('form').getByRole('button', { name: '로그인', exact: true }).click()
  await expect(page.getByRole('heading', { name: '초기 비밀번호 변경' })).toBeVisible()
  expect((await page.request.get('/api/workspaces')).status()).toBe(403)
  expect((await page.request.post('/api/invitations/accept', { data: { token } })).status()).toBe(403)
  await page.reload()
  await expect(page.getByRole('heading', { name: '초기 비밀번호 변경' })).toBeVisible()
  await page.getByLabel('초기 비밀번호', { exact: true }).fill(initialPassword)
  await page.getByLabel('새 비밀번호', { exact: true }).fill('private-owner-password-1234')
  await page.getByLabel('새 비밀번호 확인', { exact: true }).fill('private-owner-password-1234')
  await page.getByRole('button', { name: '변경하기', exact: true }).click()
  await page.getByRole('button', { name: '초대 수락', exact: true }).click()
  await expect(page.getByRole('button', { name: '구성원 · 초대', exact: true })).toBeVisible()
  const own = await (await page.request.get('/api/workspaces')).json()
  expect(own.workspaces.map((w: { id: string; role: string }) => [w.id, w.role])).toEqual([['default', 'admin']])
  expect((await page.request.post('/api/workspaces/default/invitations/account', { data: { username: 'forbidden.owner', name: '권한 없음' } })).status()).toBe(403)
  expect((await request.post('/api/auth/login', { data: { username: 'delivery.owner', password: initialPassword } })).status()).toBe(401)
})
