import { test, expect } from '@playwright/test'

test('mentors receive a replacement link after reload without replacing their password or role', async ({ page, request }) => {
  const admin = await (await request.post('/api/login', { data: { password: 'test-only-password-1234' } })).json()
  const headers = { Authorization: `Bearer ${admin.token}` }
  const workspace = await (await request.post('/api/workspaces', { headers, data: { name: '초대 링크 재발급 테스트' } })).json()
  await page.context().addCookies([{ name: 'learningops_session', value: admin.token, url: 'http://127.0.0.1:5174', httpOnly: true }])
  await page.goto(`/?workspace=${workspace.id}#members`)
  await page.getByLabel('초대할 아이디').fill('renew.ui.mentor')
  await page.getByLabel('멘토 이름').fill('재발급 멘토')
  await page.getByRole('button', { name: '계정과 초대 링크 만들기', exact: true }).click()
  const originalMessage = await page.getByLabel('전달할 초대 안내문').inputValue()
  const password = originalMessage.match(/초기 비밀번호: (\S+)/)![1]
  const originalLink = await page.getByLabel('초대 링크', { exact: true }).inputValue()
  const row = page.locator('.membership-history').getByRole('row').filter({ hasText: 'renew.ui.mentor' })
  await row.getByRole('button', { name: '초대 링크 재발급', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '초대 링크 재발급 완료' })
  await expect(dialog).toBeVisible()
  const replacement = await dialog.getByLabel('재발급된 초대 링크').inputValue()
  expect(replacement).not.toBe(originalLink)
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write'])
  await dialog.getByRole('button', { name: '새 링크 복사', exact: true }).click()
  await expect(dialog.getByRole('status')).toContainText('복사했습니다')
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(replacement)
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 950 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `test-results/invitation-reissue-${width}.png`, fullPage: true, animations: 'disabled' })
  }
  await dialog.getByRole('button', { name: '확인', exact: true }).click()
  await expect(page.getByLabel('초대 링크', { exact: true })).toHaveValue(replacement)
  expect(await page.getByLabel('전달할 초대 안내문').inputValue()).toContain(password)
  expect(await page.getByLabel('전달할 초대 안내문').inputValue()).not.toContain(originalLink)
  expect((await request.post('/api/invitations/preview', { data: { token: new URL(originalLink).hash.slice(8) } })).status()).toBe(410)
  await page.reload()
  await row.getByRole('button', { name: '초대 링크 재발급', exact: true }).click()
  const latestLink = await dialog.getByLabel('재발급된 초대 링크').inputValue()
  expect(latestLink).not.toBe(replacement)
  const token = new URL(latestLink).hash.slice(8)
  const preview = await (await request.post('/api/invitations/preview', { data: { token } })).json()
  expect(preview.role).toBe('instructor'); expect(preview.mentorType).toBe('main')
  const login = await (await request.post('/api/auth/login', { data: { username: 'renew.ui.mentor', password } })).json()
  const changed = await (await request.post('/api/auth/password', { headers: { Authorization: `Bearer ${login.token}` }, data: { currentPassword: password, newPassword: 'renew-ui-personal-password' } })).json()
  expect((await request.post('/api/invitations/accept', { headers: { Authorization: `Bearer ${changed.token}` }, data: { token } })).ok()).toBe(true)
  await page.reload()
  await expect(row).toContainText('수락 완료')
  await expect(row.getByRole('button', { name: '초대 링크 재발급', exact: true })).toHaveCount(0)
})
