import { test, expect } from '@playwright/test'

test('name-only workspace creation and issued mentor invitation guide the recipient through first login', async ({ page, browser }) => {
  test.setTimeout(60000)
  await page.goto('/')
  await page.getByRole('button', { name: '관리자 로그인', exact: true }).click()
  await page.getByLabel('관리자 비밀번호').fill('test-only-password-1234')
  await page.getByRole('button', { name: '로그인', exact: true }).click()
  await page.getByRole('button', { name: '워크스페이스 만들기', exact: true }).click()
  const modal = page.getByRole('dialog', { name: '워크스페이스 만들기' })
  await expect(modal.getByLabel('Discord 서버 ID')).not.toBeVisible()
  await modal.getByLabel('워크스페이스 이름').fill('처음 함께하는 교육')
  await modal.getByRole('button', { name: '워크스페이스 만들기', exact: true }).click()
  await expect(modal).not.toBeVisible()
  await expect(page.getByRole('button', { name: '워크스페이스 선택' })).toContainText('처음 함께하는 교육')
  await page.getByRole('navigation').getByRole('button', { name: '구성원 · 초대' }).click()
  await expect(page.getByRole('radio', { name: /새 계정 만들기/ })).toBeChecked()
  const username = await page.getByLabel('초대할 아이디').inputValue()
  expect(username).toMatch(/^member\.[a-f0-9]{8}$/)
  await page.getByLabel('멘토 이름').fill('신규 멘토')
  await page.getByLabel('멘토 구분').selectOption('group')
  await expect(page.getByRole('button', { name: '조 구성 화면 열기' })).toBeVisible()
  await expect(page.getByRole('button', { name: '계정과 초대 링크 만들기' })).toBeDisabled()
  await page.getByLabel('멘토 구분').selectOption('main')
  for (const width of [1440, 390, 360]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await page.getByRole('button', { name: '계정과 초대 링크 만들기' }).click()
  await expect(page.getByRole('heading', { name: '초대 안내문이 준비됐습니다' })).toBeVisible()
  const delivery = await page.getByLabel('전달할 초대 안내문').inputValue()
  expect(delivery).toContain('처음 함께하는 교육')
  expect(delivery).toContain(username)
  const initialPassword = delivery.match(/초기 비밀번호: (\S+)/)![1]
  const link = await page.getByLabel('초대 링크', { exact: true }).inputValue()
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.getByRole('button', { name: '초대 안내문 복사', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('복사했습니다')
  expect((await page.evaluate(() => navigator.clipboard.readText())).replace(/\r\n/g, '\n')).toBe(delivery)

  const guest = await browser.newContext()
  try {
    const recipient = await guest.newPage()
    await recipient.goto(link)
    await expect(recipient.getByLabel('아이디', { exact: true })).toHaveValue(username)
    await expect(recipient.getByRole('button', { name: '회원가입', exact: true })).toHaveCount(0)
    await expect(recipient.getByRole('button', { name: '관리자 로그인', exact: true })).toHaveCount(0)
    for (const width of [1440, 390, 360]) {
      await recipient.setViewportSize({ width, height: 900 })
      expect(await recipient.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    }
    await recipient.getByLabel('비밀번호', { exact: true }).fill(initialPassword)
    await recipient.locator('form').getByRole('button', { name: '로그인', exact: true }).click()
    await expect(recipient.getByText('초대 링크를 다시 열 필요는 없습니다.', { exact: false })).toBeVisible()
    await recipient.getByLabel('초기 비밀번호', { exact: true }).fill(initialPassword)
    await recipient.getByLabel('새 비밀번호', { exact: true }).fill('local-mentor-test-password')
    await recipient.getByLabel('새 비밀번호 확인', { exact: true }).fill('local-mentor-test-password')
    await recipient.getByRole('button', { name: '변경하기', exact: true }).click()
    await recipient.getByRole('button', { name: '초대 수락', exact: true }).click()
    await expect(recipient.getByRole('heading', { name: '멘토 활동 관리' })).toBeVisible()
  } finally { await guest.close() }
})

test('a different signed-in account can return to the same invitation; invalid links offer recovery', async ({ page, request }) => {
  const login = await (await request.post('/api/login', { data: { password: 'test-only-password-1234' } })).json()
  const invite = await (await request.post('/api/workspaces/default/invitations', { headers: { Authorization: `Bearer ${login.token}` }, data: { username: 'invitation.other', role: 'instructor' } })).json()
  await page.context().addCookies([{ name: 'learningops_session', value: login.token, url: 'http://127.0.0.1:5174', httpOnly: true }])
  await page.goto(`/#invite=${invite.token}`)
  await expect(page.getByRole('heading', { name: '초대받은 계정으로 로그인하세요' })).toBeVisible()
  await expect(page.getByRole('button', { name: '초대 수락', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '다른 계정으로 로그인', exact: true }).click()
  await expect(page.getByLabel('아이디', { exact: true })).toHaveValue('invitation.other')
  await expect(page).toHaveURL(new RegExp(`#invite=${invite.token}$`))
  await page.reload()
  await expect(page.getByLabel('아이디', { exact: true })).toHaveValue('invitation.other')
  await expect(page.getByLabel('이름', { exact: true })).toBeVisible()
  await page.goto('/#invite=invalid-invitation-token')
  await page.reload()
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(page.getByRole('button', { name: '다시 확인', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '로그인 화면으로', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'LMS 로그인', exact: true })).toBeVisible()
})
