import { test, expect, type Page } from '@playwright/test'

async function switchTo(page: Page, name: string) {
  const mobile = page.getByRole('button', { name: '메뉴 열기' })
  if (await mobile.isVisible()) await mobile.click()
  await page.getByRole('button', { name: '워크스페이스 선택', exact: true }).click()
  await page.getByLabel('워크스페이스 목록', { exact: true }).getByRole('button', { name: new RegExp(`^${name}`) }).click()
  await expect(page).toHaveURL(/workspace=/)
}

for (const demo of [false, true]) test(`${demo ? 'demo' : 'API'} creates independent workspaces and restores the selected workspace on reload`, async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto(demo ? '/?demo=1' : '/')
  if (!demo) {
    await page.getByRole('button', { name: '관리자 로그인', exact: true }).click()
    await page.getByLabel('관리자 비밀번호').fill('test-only-password-1234')
    await page.getByRole('button', { name: '로그인', exact: true }).click()
  }
  await expect(page.getByRole('heading', { name: '운영 대시보드' })).toBeVisible()
  await expect(page.getByRole('navigation').getByRole('button', { name: /아산 AX/ })).toHaveCount(0)
  await page.getByRole('button', { name: '워크스페이스 선택', exact: true }).click()
  await page.getByRole('button', { name: '새 워크스페이스', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('워크스페이스 이름').fill('세종 AX')
  await dialog.getByLabel('설명', { exact: true }).fill('별도 교육 운영')
  await dialog.getByRole('button', { name: '워크스페이스 만들기', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('button', { name: '워크스페이스 선택', exact: true })).toContainText('세종 AX')
  const createdUrl = page.url()
  await page.getByRole('button', { name: '새 과정 만들기' }).click()
  await dialog.getByLabel('과정명', { exact: true }).fill('세종 전용 과정')
  await dialog.getByLabel('과정 코드').fill('SEJONG-AX')
  await dialog.getByLabel('시작일').fill('2026-09-01')
  await dialog.getByLabel('종료일').fill('2026-12-01')
  await dialog.getByLabel('과정 소개').fill('세종 워크스페이스에만 표시')
  await dialog.getByRole('button', { name: '만들기', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('heading', { name: '세종 전용 과정' })).toBeVisible()
  await switchTo(page, '아산 AX')
  await expect(page.getByRole('button', { name: '워크스페이스 선택', exact: true })).toContainText('아산 AX')
  await expect(page.getByRole('heading', { name: '세종 전용 과정' })).toHaveCount(0)
  await page.getByRole('navigation').getByRole('button', { name: 'Discord 채널 설정' }).click()
  await page.getByRole('button', { name: '상세 설정 열기' }).click()
  await page.getByLabel('설정 이름', { exact: true }).fill('저장하지 않은 아산 구성')
  await switchTo(page, '세종 AX')
  await page.getByRole('button', { name: '상세 설정 열기' }).click()
  await expect(page.getByLabel('설정 이름', { exact: true })).toHaveValue('AX 교육 서버')
  await page.reload()
  await expect(page.getByRole('button', { name: '워크스페이스 선택', exact: true })).toContainText('세종 AX')
  expect(new URL(page.url()).search).toBe(new URL(createdUrl).search)
  await page.getByRole('navigation').getByRole('button', { name: '대시보드', exact: true }).click()
  await expect(page.getByRole('heading', { name: '세종 전용 과정' })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await switchTo(page, '아산 AX')
  await expect(page.getByRole('heading', { name: '세종 전용 과정' })).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: '메뉴 열기' }).click()
  await page.getByRole('button', { name: '워크스페이스 선택', exact: true }).click()
  await page.screenshot({ path: `test-results/workspaces-${demo ? 'demo' : 'api'}-mobile.png`, fullPage: true })
  expect(errors).toEqual([])
})
