import { test, expect } from '@playwright/test'

test('production: one-time administrator setup, cookie login, password rotation and logout', async ({ page, request, context }) => {
  const base = 'http://localhost:3003'
  const setupKey = 'production-setup-key-123456'
  const preflight = await request.fetch(`${base}/api/auth/setup`, { method: 'OPTIONS', headers: { Origin: 'https://actual-service.onrender.com', 'Access-Control-Request-Method': 'POST' } })
  expect(preflight.status()).toBe(204)
  expect(preflight.headers()['access-control-allow-origin']).toBe('https://actual-service.onrender.com')
  expect((await request.fetch(`${base}/api/auth/setup`, { method: 'OPTIONS', headers: { Origin: 'https://untrusted.example', 'X-Forwarded-Host': 'untrusted.example', 'Access-Control-Request-Method': 'POST' } })).status()).toBe(403)
  expect((await request.post(`${base}/api/login`, { data: { password: setupKey } })).status()).toBe(401)
  expect((await request.post(`${base}/api/auth/setup`, { headers: { Origin: 'https://untrusted.example' }, data: {} })).status()).toBe(403)
  await page.goto(`${base}/?demo=1`)
  await expect(page.getByRole('button', { name: '데모 둘러보기' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '관리자 로그인', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '최초 관리자 등록', exact: true }).click()
  await page.getByLabel('이름', { exact: true }).fill('운영 관리자')
  await page.getByLabel('아이디', { exact: true }).fill('platform.owner')
  await page.getByLabel('비밀번호', { exact: true }).fill('production-password-123456')
  await page.getByLabel('비밀번호 확인', { exact: true }).fill('production-password-123456')
  await page.getByLabel('관리자 설정 키', { exact: true }).fill(setupKey)
  await page.setViewportSize({ width: 390, height: 1000 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/production-setup-mobile.png', fullPage: true })
  await page.getByRole('button', { name: '관리자 계정 만들기' }).click()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await expect(page.getByRole('heading', { name: '운영 대시보드', exact: true })).toBeVisible()
  const cookie = (await context.cookies()).find(item => item.name === 'learningops_session')!
  expect(cookie).toMatchObject({ httpOnly: true, secure: true, sameSite: 'Strict', path: '/api' })
  await page.reload()
  await expect(page.getByRole('heading', { name: '운영 대시보드', exact: true })).toBeVisible()
  expect((await request.post(`${base}/api/auth/setup`, { data: { username: 'second.owner', name: '다른 관리자', password: 'production-password-123456', setupKey } })).status()).toBe(409)
  const other = await (await request.post(`${base}/api/auth/login`, { data: { username: 'platform.owner', password: 'production-password-123456' } })).json()
  await page.getByRole('button', { name: '비밀번호 변경', exact: true }).click()
  await page.getByLabel('현재 비밀번호', { exact: true }).fill('production-password-123456')
  await page.getByLabel('새 비밀번호', { exact: true }).fill('changed-production-password-123456')
  await page.getByLabel('새 비밀번호 확인', { exact: true }).fill('changed-production-password-123456')
  await page.getByRole('button', { name: '변경하기', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('비밀번호를 변경했습니다.')
  expect((await request.get(`${base}/api/auth/me`, { headers: { Authorization: `Bearer ${other.token}` } })).status()).toBe(401)
  await page.getByRole('dialog').getByRole('button', { name: '닫기', exact: true }).last().click()
  await page.reload()
  await expect(page.getByRole('heading', { name: '운영 대시보드', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '로그아웃', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'LMS 로그인', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '최초 관리자 등록', exact: true })).toHaveCount(0)
  expect((await page.request.get(`${base}/api/auth/me`)).status()).toBe(401)
  await page.getByLabel('아이디', { exact: true }).fill('platform.owner')
  await page.getByLabel('비밀번호', { exact: true }).fill('changed-production-password-123456')
  await page.locator('form').getByRole('button', { name: '로그인', exact: true }).click()
  await expect(page.getByRole('heading', { name: '운영 대시보드', exact: true })).toBeVisible()
  expect(await page.evaluate(() => Object.keys(localStorage).some(key => /token|session|password/i.test(key)))).toBe(false)
})
