import { test, expect } from '@playwright/test'

test('invited workspace admin configures groups before Discord and can reassign a mentor from LMS', async ({ page, request }) => {
  const platform = await (await request.post('/api/login', { data: { password: 'test-only-password-1234' } })).json()
  const platformHeaders = { Authorization: `Bearer ${platform.token}` }
  const workspace = await (await request.post('/api/workspaces', { headers: platformHeaders, data: { name: '전체 운영 흐름' } })).json()
  const invitation = await (await request.post(`/api/workspaces/${workspace.id}/invitations`, { headers: platformHeaders, data: { username: 'flow.owner', role: 'admin' } })).json()
  await page.goto(`/#invite=${invitation.token}`)
  await page.getByRole('button', { name: '회원가입', exact: true }).click()
  await page.getByLabel('이름', { exact: true }).fill('워크스페이스 담당자')
  await page.getByLabel('아이디', { exact: true }).fill('flow.owner')
  await page.getByLabel('비밀번호', { exact: true }).fill('flow-owner-password-1234')
  await page.getByLabel('비밀번호 확인', { exact: true }).fill('flow-owner-password-1234')
  await page.getByRole('button', { name: '계정 만들기' }).click()
  await page.getByRole('button', { name: '초대 수락', exact: true }).click()
  await page.getByText('관리자 설정 순서 · 화면과 버튼 안내', { exact: true }).click()
  await expect(page.getByRole('button', { name: '관리자 초대 화면 열기', exact: true })).toHaveCount(0)
  for (const width of [1440, 390, 360]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  }
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: '조 구성·서버 연결 화면 열기' }).click()
  await page.getByLabel('운영할 조 수', { exact: true }).fill('3')
  await page.getByRole('button', { name: '조 구성 저장' }).click()
  await expect(page.getByRole('status')).toContainText('조 구성을 저장했습니다.')
  const groups = await (await page.request.get(`/api/workspaces/${workspace.id}/discord/groups`)).json()
  expect(groups.teams).toHaveLength(3)
  const guildId = '923456789012345678'
  await page.getByLabel('Discord 채널 링크 또는 서버 ID').fill(guildId)
  await page.getByRole('button', { name: '서버 연결하고 계속', exact: true }).click()
  await expect(page.getByText(`연결된 서버: ${guildId}`, { exact: false })).toBeVisible()
  const botHeaders = { Authorization: 'Bearer test-only-provision-token-12345678901234567890' }
  const cfg = await (await request.post('/api/integrations/discord/onboarding/poll', { headers: botHeaders, data: { guildIds: [guildId] } })).json()
  expect(cfg.configs[0].teams).toHaveLength(3)
  expect(cfg.configs[0].enabled).toBe(true)
  await page.getByRole('button', { name: '구성원 · 초대', exact: true }).click()
  await page.getByLabel('초대할 아이디').fill('flow.mentor')
  await page.getByLabel('멘토 구분').selectOption('group')
  await page.getByLabel('1조', { exact: true }).check()
  await page.getByRole('button', { name: '초대 링크 만들기' }).click()
  const link = await page.getByLabel('초대 링크', { exact: true }).inputValue()
  const token = new URL(link).hash.slice(8)
  await page.getByRole('button', { name: '초대 수정', exact: true }).click()
  const inviteEditor = page.getByRole('dialog', { name: '초대 수정' })
  await inviteEditor.getByLabel('2조', { exact: true }).check()
  await inviteEditor.getByRole('button', { name: '저장', exact: true }).click()
  await expect(inviteEditor).not.toBeVisible()
  const preview = await (await request.post('/api/invitations/preview', { data: { token } })).json()
  expect(preview.teamIds).toHaveLength(2)
  const mentor = await (await request.post('/api/auth/register', { data: { invitationToken: token, username: 'flow.mentor', name: '조 멘토', password: 'flow-mentor-password-1234' } })).json()
  const mentorHeaders = { Authorization: `Bearer ${mentor.token}` }
  expect((await request.post('/api/invitations/accept', { headers: mentorHeaders, data: { token } })).status()).toBe(200)
  await page.reload()
  await expect(page.getByRole('button', { name: '멘토 관리', exact: true })).toHaveCount(0)
  await page.getByRole('row').filter({ hasText: 'flow.mentor' }).first().getByRole('button', { name: '수정', exact: true }).click()
  const editor = page.getByRole('dialog', { name: '구성원 수정' })
  await editor.getByLabel('활동명').fill('수정된 멘토')
  await editor.getByLabel('담당 분야').fill('데이터 분석')
  await editor.getByLabel('1조', { exact: true }).uncheck()
  await editor.getByLabel('2조', { exact: true }).check()
  await editor.getByLabel('3조', { exact: true }).check()
  await editor.getByRole('button', { name: '저장', exact: true }).click()
  await expect(page.getByRole('row').filter({ hasText: 'flow.mentor' }).first()).toContainText('2조 · 3조')
  const own = await (await request.get(`/api/workspaces/${workspace.id}/staff/onboarding`, { headers: mentorHeaders })).json()
  expect(own.teamIds).toEqual([groups.teams[1].id, groups.teams[2].id])
  expect((await request.patch(`/api/workspaces/${workspace.id}/members/${mentor.user.id}/assignment`, { headers: mentorHeaders, data: { mentorType: 'main', teamIds: [] } })).status()).toBe(403)
  await expect(page.getByRole('row').filter({ hasText: 'flow.mentor' }).first()).toContainText('수정된 멘토')
  for (const width of [1440, 390, 360]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  }
  await page.getByRole('row').filter({ hasText: 'flow.mentor' }).first().getByRole('button', { name: '삭제', exact: true }).click()
  await page.getByRole('button', { name: '워크스페이스에서 제외', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('워크스페이스에서 구성원을 제외했습니다.')
  expect((await request.get(`/api/workspaces/${workspace.id}/staff/onboarding`, { headers: mentorHeaders })).status()).toBe(403)
})

test('platform administrator edits and removes workspace administrators, and cancels pending invitations', async ({ page, request }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '관리자 로그인', exact: true }).click()
  await page.getByLabel('관리자 비밀번호').fill('test-only-password-1234')
  await page.getByRole('button', { name: '로그인', exact: true }).click()
  await expect(page.getByRole('heading', { name: '운영 대시보드' })).toBeVisible()
  const invitation = await (await page.request.post('/api/workspaces/default/invitations', { data: { username: 'editable.owner', role: 'admin' } })).json()
  const owner = await (await request.post('/api/auth/register', { data: { invitationToken: invitation.token, username: 'editable.owner', name: '운영 담당자', password: 'editable-owner-password-1234' } })).json()
  expect((await request.post('/api/invitations/accept', { headers: { Authorization: `Bearer ${owner.token}` }, data: { token: invitation.token } })).ok()).toBeTruthy()
  await page.getByRole('button', { name: '구성원 · 초대', exact: true }).click()
  const member = page.getByRole('row').filter({ hasText: 'editable.owner' }).first()
  await member.getByRole('button', { name: '수정', exact: true }).click()
  const editor = page.getByRole('dialog', { name: '구성원 수정' })
  await editor.getByLabel('활동명').fill('수정한 관리자')
  await editor.getByRole('button', { name: '저장', exact: true }).click()
  await expect(member).toContainText('수정한 관리자')
  await member.getByRole('button', { name: '삭제', exact: true }).click()
  await page.getByRole('button', { name: '워크스페이스에서 제외', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('워크스페이스에서 구성원을 제외했습니다.')
  expect((await request.get('/api/workspaces/default/members', { headers: { Authorization: `Bearer ${owner.token}` } })).status()).toBe(403)
  await page.getByLabel('초대할 아이디').fill('cancelled.owner')
  await page.getByLabel('참여 권한').selectOption('admin')
  await page.getByLabel('계정 발급 방식').selectOption('existing')
  await page.getByRole('button', { name: '초대 링크 만들기' }).click()
  const link = await page.getByLabel('초대 링크', { exact: true }).inputValue()
  await page.getByRole('row').filter({ hasText: 'cancelled.owner' }).getByRole('button', { name: '초대 취소', exact: true }).click()
  await page.getByRole('button', { name: '초대 취소 확인' }).click()
  await expect(page.getByRole('row').filter({ hasText: 'cancelled.owner' })).toContainText('취소됨')
  expect((await request.post('/api/invitations/preview', { data: { token: new URL(link).hash.slice(8) } })).status()).toBe(410)
})
