import { test, expect } from '@playwright/test'

test('invited workspace admin configures groups before Discord and can reassign a mentor from LMS', async ({ page, request }) => {
  const platform = await (await request.post('/api/login', { data: { password: 'test-only-password-1234' } })).json()
  const platformHeaders = { Authorization: `Bearer ${platform.token}` }
  const workspace = await (await request.post('/api/workspaces', { headers: platformHeaders, data: { name: '전체 운영 흐름' } })).json()
  const invitation = await (await request.post(`/api/workspaces/${workspace.id}/invitations`, { headers: platformHeaders, data: { username: 'flow.owner', role: 'admin' } })).json()
  await page.goto(`/#invite=${invitation.token}`)
  await page.getByRole('button', { name: '회원가입', exact: true }).click()
  await page.getByLabel('이름', { exact: true }).fill('워크스페이스 담당자')
  await page.getByLabel('아이디', { exact: true }).fill('flow.owner')
  await page.getByLabel('비밀번호', { exact: true }).fill('flow-owner-password-1234')
  await page.getByLabel('비밀번호 확인', { exact: true }).fill('flow-owner-password-1234')
  await page.getByRole('button', { name: '계정 만들기' }).click()
  await page.getByRole('button', { name: '초대 수락', exact: true }).click()
  await page.getByRole('button', { name: '2. 조 설정 및 Discord 구축' }).click()
  await page.getByLabel('운영할 조 수', { exact: true }).fill('3')
  await page.getByRole('button', { name: '조 구성 저장' }).click()
  await expect(page.getByRole('status')).toContainText('조 구성을 저장했습니다.')
  const groups = await (await page.request.get(`/api/workspaces/${workspace.id}/discord/groups`)).json()
  expect(groups.teams).toHaveLength(3)
  const guildId = '923456789012345678'
  await page.getByLabel('추가할 Discord 서버 ID').fill(guildId)
  await page.getByRole('button', { name: '서버 추가 및 구축', exact: true }).click()
  await expect(page.getByText(`연결된 서버: ${guildId}`, { exact: false })).toBeVisible()
  const botHeaders = { Authorization: 'Bearer test-only-provision-token-12345678901234567890' }
  const cfg = await (await request.post('/api/integrations/discord/onboarding/poll', { headers: botHeaders, data: { guildIds: [guildId] } })).json()
  expect(cfg.configs[0].teams).toHaveLength(3)
  expect(cfg.configs[0].enabled).toBe(true)
  await page.getByRole('button', { name: '구성원 · 초대', exact: true }).click()
  await page.getByLabel('초대할 아이디').fill('flow.mentor')
  await page.getByLabel('멘토 구분').selectOption('group')
  await page.getByLabel('1조', { exact: true }).check()
  await page.getByRole('button', { name: '초대 링크 만들기' }).click()
  const link = await page.getByLabel('초대 링크', { exact: true }).inputValue()
  const token = new URL(link).hash.slice(8)
  const mentor = await (await request.post('/api/auth/register', { data: { invitationToken: token, username: 'flow.mentor', name: '조 멘토', password: 'flow-mentor-password-1234' } })).json()
  const mentorHeaders = { Authorization: `Bearer ${mentor.token}` }
  expect((await request.post('/api/invitations/accept', { headers: mentorHeaders, data: { token } })).status()).toBe(200)
  await page.reload()
  await page.getByRole('button', { name: '담당 조 변경' }).click()
  const editor = page.locator('section').filter({ has: page.getByRole('heading', { name: '조 멘토 담당 조 변경' }) })
  await editor.getByLabel('1조', { exact: true }).uncheck()
  await editor.getByLabel('2조', { exact: true }).check()
  await editor.getByLabel('3조', { exact: true }).check()
  await editor.getByRole('button', { name: '담당 조 저장' }).click()
  await expect(page.getByRole('row').filter({ hasText: 'flow.mentor' }).first()).toContainText('2조 · 3조')
  const own = await (await request.get(`/api/workspaces/${workspace.id}/staff/onboarding`, { headers: mentorHeaders })).json()
  expect(own.teamIds).toEqual([groups.teams[1].id, groups.teams[2].id])
  expect((await request.patch(`/api/workspaces/${workspace.id}/members/${mentor.user.id}/assignment`, { headers: mentorHeaders, data: { mentorType: 'main', teamIds: [] } })).status()).toBe(403)
  for (const width of [1440, 390, 360]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  }
})
