import { test, expect } from '@playwright/test'

test('production workspace owner issues a student who must set profile and password before learning', async ({ page, request, browser }) => {
  const site = 'http://localhost:3005', api = site + '/api'
  const setup = await request.post(api + '/auth/setup', { data: { username: 'issuing.platform', name: '총관리자', password: 'platform-password-1234', setupKey: 'student-setup-key-123456' } })
  expect(setup.status()).toBe(201)
  const platform = await setup.json(), headers = { Authorization: 'Bearer ' + platform.token }
  const workspace = await (await request.post(api + '/workspaces', { headers, data: { name: '학생 발급 실습', guildId: '983456789012345670' } })).json()
  const base = api + '/workspaces/' + workspace.id
  const groups = await (await request.get(base + '/discord/groups', { headers })).json()
  const teams = await (await request.post(base + '/discord/groups', { headers, data: { count: 2, revision: groups.revision } })).json()
  const invite = await (await request.post(base + '/invitations/account', { headers, data: { username: 'issuing.owner', name: '워크스페이스 관리자' } })).json()
  const initial = await (await request.post(api + '/auth/login', { data: { username: invite.username, password: invite.initialPassword } })).json()
  const owner = await (await request.post(api + '/auth/password', { headers: { Authorization: 'Bearer ' + initial.token }, data: { currentPassword: invite.initialPassword, newPassword: 'owner-password-1234' } })).json()
  const ownerHeaders = { Authorization: 'Bearer ' + owner.token }
  expect((await request.post(api + '/invitations/accept', { headers: ownerHeaders, data: { token: invite.token } })).status()).toBe(200)
  expect((await (await request.get(api + '/auth/config')).json()).studentRegistrationEnabled).toBe(false)
  for (const endpoint of ['/auth/student/register', '/auth/register']) expect((await request.post(api + endpoint, { data: { username: 'self.signup', password: 'should-not-work' } })).status()).toBe(403)
  await page.goto(site + '/#signup')
  await expect(page.getByRole('button', { name: '회원가입', exact: true })).toHaveCount(0)
  await page.getByLabel('아이디', { exact: true }).fill('issuing.owner')
  await page.getByLabel('비밀번호', { exact: true }).fill('owner-password-1234')
  await page.locator('button[type=submit]').click()
  await page.getByRole('button', { name: '학생 계정 발급', exact: true }).click()
  await expect(page.getByRole('button', { name: '전체 계정 관리', exact: true })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: '기본 정보', exact: true })).toHaveCount(0)
  await page.getByLabel('발급할 아이디').fill('issued.student')
  await page.getByLabel('배정할 과정 · 조').selectOption(teams.teams[0].id)
  await page.getByRole('button', { name: '학생 계정·초기 비밀번호 발급' }).click()
  const dialog = page.getByRole('dialog', { name: '학생 계정 발급 완료' })
  const credentials = await dialog.getByLabel('학생에게 전달할 계정 정보').inputValue()
  const initialPassword = credentials.split('\n').find(line => line.startsWith('초기 비밀번호: '))!.replace('초기 비밀번호: ', '')
  expect(initialPassword.length).toBe(24)
  await dialog.getByRole('button', { name: '전달 정보 확인 완료' }).click()
  await expect(page.getByRole('row').filter({ hasText: 'issued.student' })).toContainText('첫 로그인 설정 대기')
  expect((await request.post(base + '/student-accounts', { headers: ownerHeaders, data: { username: 'issued.student', teamId: teams.teams[0].id } })).status()).toBe(409)
  const foreign = await (await request.post(api + '/workspaces', { headers, data: { name: '다른 워크스페이스' } })).json()
  expect((await request.post(api + '/workspaces/' + foreign.id + '/student-accounts', { headers: ownerHeaders, data: { username: 'wrong.workspace', teamId: teams.teams[0].id } })).status()).toBe(403)
  const login = await (await request.post(api + '/auth/login', { data: { username: 'issued.student', password: initialPassword } })).json()
  const firstHeaders = { Authorization: 'Bearer ' + login.token }
  for (const path of ['/workspaces', '/me/admissions']) expect((await request.get(api + path, { headers: firstHeaders })).status()).toBe(403)
  expect((await request.post(api + '/auth/password', { headers: firstHeaders, data: { currentPassword: initialPassword, newPassword: 'student-password-1234' } })).status()).toBe(403)
  expect((await request.post(base + '/me/verification', { headers: firstHeaders, data: {} })).status()).toBe(403)
  const studentContext = await browser.newContext()
  const student = await studentContext.newPage()
  try {
    await student.goto(site)
    await student.getByLabel('아이디', { exact: true }).fill('issued.student')
    await student.getByLabel('비밀번호', { exact: true }).fill(initialPassword)
    await student.locator('button[type=submit]').click()
    await expect(student.getByRole('heading', { name: '내 정보와 비밀번호 설정' })).toBeVisible()
    for (const width of [1440, 390, 360]) {
      await student.setViewportSize({ width, height: 1000 })
      expect(await student.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
    }
    await student.screenshot({ path: 'test-results/student-first-login-360.png', fullPage: true, animations: 'disabled' })
    await student.getByLabel('이름', { exact: true }).fill('직접 입력한 학생')
    await student.getByLabel('초기 비밀번호', { exact: true }).fill(initialPassword)
    await student.getByLabel('새 비밀번호', { exact: true }).fill('student-password-1234')
    await student.getByLabel('새 비밀번호 확인', { exact: true }).fill('student-password-1234')
    await student.getByRole('button', { name: '설정 완료하고 시작하기' }).click()
    await expect(student.getByRole('heading', { name: '나의 학습', exact: true })).toBeVisible()
    await expect(student.getByRole('heading', { name: '워크스페이스 참여 현황' })).toBeVisible()
    await expect(student.getByText('직접 입력한 학생 · issued.student')).toBeVisible()
    expect((await request.get(api + '/auth/me', { headers: firstHeaders })).status()).toBe(401)
    expect((await student.request.post(base + '/student-accounts', { data: { username: 'escalated.student', teamId: teams.teams[0].id } })).status()).toBe(403)
    const beforeReload = await student.request.get(api + '/auth/me')
    expect((await beforeReload.json()).user.mustCompleteProfile).toBe(false)
    await student.reload()
    await expect(student.getByRole('heading', { name: '나의 학습', exact: true })).toBeVisible()
    expect(await student.evaluate(() => Object.keys(localStorage).some(key => /password|token|secret/i.test(key)))).toBe(false)
  } finally { await studentContext.close() }
  await page.getByRole('button', { name: '계정 상태 새로고침' }).click()
  const row = page.getByRole('row').filter({ hasText: 'issued.student' })
  await expect(row).toContainText('직접 입력한 학생')
  await expect(row).toContainText('설정 완료')
  for (const width of [1440, 390, 360]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  }
  await page.screenshot({ path: 'test-results/student-account-issuer-360.png', fullPage: true, animations: 'disabled' })
})
