import { test, expect } from '@playwright/test'
import { resolve } from 'node:path'

test('Discord setup imports exact team names before a server is connected and retains the result dialog', async ({ page }) => {
  await page.request.post('/api/login', { data: { password: 'test-only-password-1234' } })
  const w = await (await page.request.post('/api/workspaces', { data: { name: '명단으로 Discord 조 준비' } })).json()
  await page.goto(`/?workspace=${w.id}#discord`)
  await page.getByLabel('참여자 명단 엑셀').setInputFiles(resolve('tests/fixtures/participant-roster.xlsx'))
  const preview = page.getByRole('dialog', { name: '엑셀 등록 검증 결과' })
  await expect(preview).toContainText('1팀 1명'); await expect(preview).toContainText('3팀 1명')
  await preview.getByRole('button', { name: '조 2개 준비 적용' }).click()
  const result = page.getByRole('dialog', { name: '엑셀 등록 처리 결과' })
  await expect(result).toContainText('조 2개 준비 완료'); await expect(result).toContainText('실패 1명')
  await result.getByRole('button', { name: '결과 확인' }).click()
  await expect(page.getByRole('heading', { name: '2. Discord 서버 연결' })).toBeVisible()
  const groups = await (await page.request.get(`/api/workspaces/${w.id}/discord/groups`)).json()
  expect(groups.teams.map((t: { name: string }) => t.name)).toEqual(['1팀','3팀'])
  expect((await (await page.request.get(`/api/workspaces/${w.id}/student-accounts`)).json()).accounts).toHaveLength(0)
})

test('roster template, preview cancellation, partial apply, retry, profile editing and scoped removal', async ({ page }) => {
  test.setTimeout(90000)
  await page.request.post('/api/login', { data: { password: 'test-only-password-1234' } })
  const w = await (await page.request.post('/api/workspaces', { data: { name: '엑셀 명단 수업', guildId: '893456789012345678' } })).json()
  const base = `/api/workspaces/${w.id}`
  await page.goto(`/?workspace=${w.id}#student-accounts`)
  const download = await page.request.get('/templates/student-roster-template.xlsx')
  expect(download.status()).toBe(200); expect((await download.body()).subarray(0,2).toString()).toBe('PK')
  const upload = () => page.getByLabel('참여자 명단 엑셀').setInputFiles(resolve('tests/fixtures/participant-roster.xlsx'))
  await upload()
  const preview = page.getByRole('dialog', { name: '엑셀 등록 검증 결과' })
  await expect(preview).toContainText('등록 가능 2명'); await expect(preview).toContainText('실패 1명'); await expect(preview).toContainText('제외 1명')
  await preview.getByRole('button', { name: '취소 · 적용하지 않기' }).click()
  expect((await (await page.request.get(base + '/student-accounts')).json()).accounts).toHaveLength(0)
  expect((await (await page.request.get(base + '/discord/groups')).json()).teams).toHaveLength(0)
  await upload(); await preview.getByRole('button', { name: '등록 가능 2명 적용' }).click()
  const result = page.getByRole('dialog', { name: '엑셀 등록 처리 결과' })
  await expect(result).toContainText('등록 성공 2명'); await expect(result).toContainText('실패 1명')
  await result.getByRole('button', { name: '결과 확인', exact: true }).click()
  const student = page.getByRole('row').filter({ hasText: 'demo-01' })
  await expect(student).toContainText('예제 대학')
  await upload(); await expect(preview).toContainText('기존 계정 2명')
  await expect(preview.getByRole('button', { name: '등록 가능 0명 적용' })).toBeDisabled()
  await preview.getByRole('button', { name: '취소 · 적용하지 않기' }).click()
  await student.getByRole('button', { name: '정보 수정', exact: true }).click()
  const edit = page.getByRole('dialog', { name: '수강생 정보 수정' })
  await edit.getByLabel('성명', { exact: true }).fill('수정한 학생')
  await edit.getByLabel('학교', { exact: true }).fill('수정 대학')
  await edit.getByRole('button', { name: '수강생 정보 저장' }).click()
  await expect(student).toContainText('수정 대학')
  await page.setViewportSize({ width: 390, height: 900 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await student.getByRole('button', { name: '수강생 삭제' }).click()
  const removal = page.getByRole('dialog', { name: '수강생 삭제 확인' })
  await expect(removal).toContainText('로그인 계정과 다른 워크스페이스 소속')
  await removal.getByRole('button', { name: '취소', exact: true }).click()
  await expect(student).toBeVisible()
  await student.getByRole('button', { name: '수강생 삭제' }).click()
  await removal.getByRole('button', { name: '이 워크스페이스에서 삭제' }).click()
  await expect(student).toHaveCount(0)
  const login = await page.request.post('/api/auth/login', { data: { username: 'demo-01', password: 'bdaxuser1!' } })
  expect(login.status()).toBe(200)
})
