import { test, expect, type Page } from '@playwright/test'

async function login(page: Page) {
  await page.goto('/')
  await page.getByRole('button', { name: '관리자 로그인', exact: true }).click()
  await expect(page.getByRole('heading', { name: '관리자 로그인' })).toBeVisible()
  await page.getByLabel('관리자 비밀번호').fill('test-only-password-1234')
  await page.getByRole('button', { name: '로그인', exact: true }).click()
  await expect(page.getByRole('heading', { name: '운영 대시보드' })).toBeVisible()
}
test('API authentication and origin restrictions', async ({ request }) => {
  expect((await request.get('/api/workspace')).status()).toBe(401)
  expect((await request.post('/api/login', { data: { password: 'incorrect' } })).status()).toBe(401)
  expect((await request.post('/api/login', { headers: { Origin: 'https://untrusted.example' }, data: { password: 'test-only-password-1234' } })).status()).toBe(403)
})
test('create course, learner, attendance and score, persist reload, and validate errors', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await login(page)
  await page.getByRole('button', { name: '새 과정 만들기' }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('과정명', { exact: true }).fill('AX LearningOps 테스트 과정')
  await dialog.getByLabel('과정 코드').fill('E2E-AX')
  await dialog.getByLabel('시작일').fill('2026-09-01')
  await dialog.getByLabel('종료일').fill('2026-12-01')
  await dialog.getByLabel('과정 소개').fill('운영 검증 과정')
  await dialog.getByRole('button', { name: '만들기', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('navigation').getByRole('button', { name: '수강생 관리' }).click()
  await page.getByRole('button', { name: '수강생 등록' }).click()
  await dialog.getByLabel('이름', { exact: true }).fill('김테스트')
  await dialog.getByLabel('이메일').fill('learner@example.com')
  await dialog.getByLabel('Discord ID').fill('333456789012345678')
  await dialog.getByRole('button', { name: '저장', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('cell', { name: '김테스트', exact: true })).toBeVisible()
  await page.getByRole('navigation').getByRole('button', { name: '출결 관리' }).click()
  await page.getByRole('button', { name: '회차 시작', exact: true }).click()
  await expect(page.locator('.attendance-panel').getByRole('status')).toHaveText('회차를 시작했습니다.')
  await page.getByRole('group', { name: '김테스트 출결 상태', exact: true }).getByRole('button', { name: '출석', exact: true }).click()
  await page.getByLabel('등록·정정 사유').fill('운영자 확인')
  await page.getByRole('button', { name: '출결 일괄 저장', exact: true }).click()
  await expect(page.locator('.attendance-panel').getByRole('status')).toHaveText('명단 출결을 저장했습니다.')
  await expect(page.getByRole('button', { name: '출결 일괄 저장', exact: true })).toBeDisabled()
  await page.getByRole('navigation').getByRole('button', { name: '성적 관리' }).click()
  await page.getByRole('button', { name: '성적 등록' }).click()
  await dialog.getByLabel('수강생', { exact: true }).selectOption({ label: '김테스트' })
  await dialog.getByLabel('평가항목').fill('프로젝트')
  await dialog.getByLabel('점수', { exact: true }).fill('110')
  await dialog.getByRole('button', { name: '저장', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('최대 배점')
  await dialog.getByLabel('점수', { exact: true }).fill('85')
  await dialog.getByRole('button', { name: '저장', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.reload()
  await expect(page.getByRole('cell', { name: '85', exact: true })).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'CSV 내보내기' }).click()
  expect((await downloadPromise).suggestedFilename()).toBe('성적.csv')
  // Seed a legacy mentor to verify existing booking history remains usable after UI consolidation.
  const state = await (await page.request.get('/api/workspace')).json()
  expect((await page.request.patch('/api/workspace', { data: { revision: state.revision, changes: [{ kind: 'mentors', value: { id: 'legacy-fixture', name: '박멘토', discordId: '444456789012345678', bio: '' } }] } })).ok()).toBeTruthy()
  await page.reload()
  await page.getByRole('navigation').getByRole('button', { name: '멘토링 일정' }).click()
  await page.getByRole('button', { name: '일정 등록', exact: true }).click()
  await dialog.getByLabel('멘토링 주제').fill('API 연동 멘토링')
  await dialog.getByRole('combobox', { name: '담당 멘토' }).selectOption({ label: '박멘토' })
  await dialog.getByRole('combobox', { name: '수강생', exact: true }).selectOption({ label: '김테스트' })
  await dialog.getByLabel('날짜', { exact: true }).fill('2026-10-02')
  await dialog.getByRole('button', { name: '만들기', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('button', { name: '승인', exact: true }).click()
  await expect(page.getByRole('cell', { name: '예약 확정', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '취소', exact: true }).click()
  await expect(page.getByRole('cell', { name: '취소', exact: true }).first()).toBeVisible()
  await page.reload()
  await expect(page.getByRole('cell', { name: '취소', exact: true }).first()).toBeVisible()
  expect(errors).toEqual([])
})
test('desktop, tablet and mobile layouts have no page overflow', async ({ page }) => {
  await page.goto('/?demo=1')
  for (const [width, height] of [[1440, 1000], [820, 1180], [390, 844], [360, 800]]) {
    await page.setViewportSize({ width, height })
    await expect(page.getByRole('heading', { name: '운영 대시보드' })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
    await page.screenshot({ path: `test-results/dashboard-${width}.png`, fullPage: true, animations: 'disabled' })
  }
  await page.getByRole('button', { name: '메뉴 열기' }).click()
  await page.getByRole('navigation').getByRole('button', { name: '출결 관리' }).click()
  await expect(page.getByRole('heading', { name: '출결 관리', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '메뉴 닫기' })).not.toBeVisible()
})
test('unconnected server actions are disabled and notices stay drafts', async ({ page }) => {
  await login(page)
  await page.getByRole('navigation').getByRole('button', { name: '봇 · 서버 관리' }).click()
  await page.getByRole('button', { name: '서버 추가' }).click()
  await page.getByRole('dialog').getByLabel('서버 이름').fill('production-server')
  await page.getByRole('dialog').getByRole('button', { name: '서버 등록' }).click()
  await expect(page.getByRole('button', { name: '실행 제어 미연결' })).toBeDisabled()
  await page.getByRole('navigation').getByRole('button', { name: '공지 관리' }).click()
  await page.getByRole('button', { name: '공지 등록' }).click()
  await page.getByRole('dialog').getByLabel('제목').fill('운영 공지')
  await page.getByRole('dialog').getByLabel('내용').fill('발송되지 않는 초안')
  await page.getByRole('dialog').getByRole('button', { name: '저장', exact: true }).click()
  await expect(page.getByRole('cell', { name: '운영 공지', exact: true })).toBeVisible()
})
