import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { createRuntime } from './runtime.mjs';
import { createAttendanceCodes } from './attendance-codes.mjs';
const guildId = '123456789012345678';
const selected = { courseId: 'course', date: '2026-09-18', period: 1 };
async function fixture(t) {
    const dir = mkdtempSync(join(tmpdir(), 'attendance-code-'));
    const runtime = await createRuntime(join(dir, 'test.db'), { NODE_ENV: 'test' });
    t.after(() => { runtime.close(); rmSync(dir, { recursive: true, force: true }); });
    const { store: { db }, workspaces, attendance } = runtime;
    let time = Date.now();
    const codes = createAttendanceCodes(db, workspaces, attendance, { now: () => time });
    const put = async (kind, row) => await db.prepare('INSERT INTO lms_records VALUES(?,?,?)').run(kind, row.id, JSON.stringify(row));
    const account = async (id, role, discordId) => {
        await db.prepare('INSERT INTO lms_users(id,username,name,password_hash,discord_id,guild_id,created_at,platform_role) VALUES(?,?,?,?,?,?,?,?)').run(id, id, id, 'unused', discordId, guildId, time, role === 'admin' ? 'admin' : 'student');
        await db.prepare('INSERT INTO lms_workspace_members VALUES(?,?,?,?)').run('default', id, role, time);
        await db.prepare('INSERT INTO lms_workspace_verifications VALUES(?,?,?,?,?)').run('default', id, guildId, discordId, time);
        return { id, username: id, role: role === 'admin' ? 'admin' : 'student', discordId };
    };
    await db.prepare('INSERT INTO lms_workspace_guilds VALUES(?,?)').run(guildId, 'default');
    const admin = await account('owner', 'admin', '123456789012345680');
    const mentor = await account('mentor', 'instructor', '123456789012345681');
    const student = await account('student', 'student', '123456789012345682');
    const other = await account('other', 'student', '123456789012345683');
    await put('courses', { id: 'course', title: '테스트 과정' });
    await put('teams', { id: 't1', name: '1조', courseId: 'course' });
    await put('teams', { id: 't2', name: '2조', courseId: 'course' });
    for (const [user, team] of [[student, '1조'], [other, '2조']])
        await put('learners', { id: user.id, discordId: user.discordId, courseId: 'course', name: user.id, team, status: '정상' });
    await workspaces.assignMentor('default', mentor.id, { mentorType: 'group', teamIds: ['t1'] }, admin);
    const view = async () => await attendance.view('default', selected, admin);
    const save = async (action, entries = []) => await attendance.save('default', { ...selected, action, entries, revision: (await view()).revision, requestId: randomUUID() }, admin);
    const issue = async (user = admin, raw = {}) => await codes.issue('default', { ...selected, ...raw }, user);
    const check = async (code, user = student, guild = guildId) => await codes.checkIn({ guildId: guild, discordId: user.discordId, code });
    return { db, codes, workspaces, admin, mentor, student, other, put, view, save, issue, check, advance: ms => { time += ms; } };
}
test('verified students check in once per round, change roster revision, and cannot overwrite mentor corrections', async (t) => {
    const f = await fixture(t);
    await assert.rejects(async () => await f.issue(), { status: 409 });
    await f.save('start');
    const issued = await f.issue(), before = (await f.view()).revision;
    assert.match(issued.code, /^\d{6}$/);
    assert.ok(!JSON.stringify(await f.db.prepare('SELECT * FROM lms_attendance_codes').get()).includes(issued.code));
    assert.equal((await f.check(issued.code)).alreadyRecorded, false);
    assert.notEqual((await f.view()).revision, before);
    assert.equal((await f.check(issued.code)).alreadyRecorded, true);
    assert.equal((await f.view()).history.length, 1);
    await f.save('save', [{ studentId: 'student', status: '지각', reason: '멘토 도착 확인' }]);
    assert.equal((await f.check(issued.code)).status, '지각');
    assert.equal((await f.check((await f.issue()).code)).status, '지각');
    assert.equal((await f.view()).counts['지각'], 1);
    assert.equal((await f.view()).history.length, 2);
});
test('expiry boundary, replacement, explicit revocation, closure and archive reject registration', async (t) => {
    const f = await fixture(t);
    await f.save('start');
    const first = await f.issue(), second = await f.issue();
    await assert.rejects(async () => await f.check(first.code), { status: 410 });
    f.advance(5 * 60000);
    await assert.rejects(async () => await f.check(second.code), { status: 410 });
    const third = await f.issue();
    await f.codes.revoke('default', selected, f.admin);
    await assert.rejects(async () => await f.check(third.code), { status: 410 });
    const fourth = await f.issue();
    await f.save('save', ['student', 'other'].map(studentId => ({ studentId, status: '결석' })));
    await f.save('close');
    await assert.rejects(async () => await f.check(fourth.code), { status: 409 });
    assert.equal((await f.codes.status('default', selected, f.admin)).active, null);
    await f.db.prepare('UPDATE lms_workspaces SET archived_at=1 WHERE id=?').run('default');
    await assert.rejects(async () => await f.check(fourth.code), { status: 403 });
});
test('guild, membership, workspace verification, enrollment and current mentor scope are enforced', async (t) => {
    const f = await fixture(t);
    await f.save('start');
    await assert.rejects(async () => await f.issue(f.student), { status: 403 });
    const issued = await f.issue(f.mentor);
    await assert.rejects(async () => await f.check(issued.code, f.other), { status: 403 });
    await assert.rejects(async () => await f.check(issued.code, f.student, '123456789012345699'), { status: 403 });
    await f.db.prepare('DELETE FROM lms_workspace_verifications WHERE user_id=?').run('student');
    await assert.rejects(async () => await f.check(issued.code), { status: 403 });
    await f.db.prepare('INSERT INTO lms_workspace_verifications VALUES(?,?,?,?,?)').run('default', 'student', guildId, f.student.discordId, 1);
    await f.db.prepare("UPDATE lms_records SET data=json_set(data,'$.status','중도탈락') WHERE kind='learners' AND id='student'").run();
    await assert.rejects(async () => await f.check(issued.code), { status: 403 });
    await f.db.prepare("UPDATE lms_records SET data=json_set(data,'$.status','정상') WHERE kind='learners' AND id='student'").run();
    await f.workspaces.assignMentor('default', f.mentor.id, { mentorType: 'group', teamIds: ['t2'] }, f.admin);
    await assert.rejects(async () => await f.check(issued.code), { status: 403 });
    await assert.rejects(async () => await f.check(issued.code, f.other), { status: 403 });
    const current = await f.issue(f.mentor);
    await f.db.prepare('DELETE FROM lms_workspace_members WHERE user_id=?').run(f.mentor.id);
    await assert.rejects(async () => await f.check(current.code, f.other), { status: 403 });
    const adminCode = await f.issue();
    await f.db.prepare('DELETE FROM lms_workspace_members WHERE user_id=?').run(f.student.id);
    await assert.rejects(async () => await f.check(adminCode.code), { status: 403 });
});
test('two mentors codes remain independent and codes cannot be retargeted to another course', async (t) => {
    const f = await fixture(t);
    await f.save('start');
    const whole = await f.issue(), group = await f.issue(f.mentor);
    await f.codes.revoke('default', selected, f.mentor);
    await assert.rejects(async () => await f.check(group.code), { status: 410 });
    assert.equal((await f.check(whole.code, f.other)).status, '출석');
    await f.db.prepare("UPDATE lms_records SET data=json_set(data,'$.courseId','another') WHERE kind='learners' AND id='student'").run();
    await assert.rejects(async () => await f.check(whole.code), { status: 403 });
});
test('failed audit rolls back attendance and revision; malformed input cannot select arbitrary identity', async (t) => {
    const f = await fixture(t);
    await f.save('start');
    const issued = await f.issue(), before = (await f.view()).revision;
    f.db.exec("CREATE TRIGGER fail_attendance BEFORE INSERT ON lms_audit WHEN NEW.action='attendance.checkin' BEGIN SELECT RAISE(ABORT,'disk failure'); END");
    await assert.rejects(async () => await f.check(issued.code), /disk failure/);
    assert.equal((await f.view()).revision, before);
    assert.equal((await f.view()).counts['출석'], 0);
    f.db.exec('DROP TRIGGER fail_attendance');
    assert.equal((await f.check(issued.code)).alreadyRecorded, false);
    await assert.rejects(async () => await f.codes.checkIn({ code: issued.code, guildId, discordId: f.student.discordId, studentId: 'other' }));
    for (const code of ['12345', '1234567', "' OR 1=1", '１２３４５６'])
        await assert.rejects(async () => await f.check(code));
});
