import express from 'express'
import { config } from 'dotenv'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { ZodError } from 'zod'
import { ApiError, createStore } from './store.mjs'
import { createRenderSync } from './render-sync.mjs'
import { createAuth } from './auth.mjs'
import { studentLearning } from './student.mjs'
import { createProvision } from './provision.mjs'
import { createWorkspaces } from './workspaces.mjs'
import { createAdmissions } from './admissions.mjs'
import { configuredOrigins } from './origins.mjs'
import { createOnboarding } from './onboarding.mjs'
import { createBotStorage } from './bot-storage.mjs'
import { createStaffFlow } from './staff-flow.mjs'
import { createOutbox } from './outbox.mjs'
import { createAssignmentAlerts } from './assignment-alerts.mjs'
import { createTeamOperations } from './team-operations.mjs'
