import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createStore } from './store.mjs';
import { createAuth } from './auth.mjs';
import { createRenderSync } from './render-sync.mjs';
import { createProvision } from './provision.mjs';
import { createWorkspaces } from './workspaces.mjs';
import { createOutbox } from './outbox.mjs';
const guildId = '123456789012345678', channelId = '223456789012345678', messageId = '323456789012345678', admin = { id: 'admin', username: 'operator', role: 'admin' };
async function fixture(t) {
    const dir = mkdtempSync(join(tmpdir(), 'outbox-')), dbPath = join(dir, 'test.db'), store = await createStore(dbPath);
    await createAuth(store.db);
    await createRenderSync(store.db);
    const provision = await createProvision(store.db), workspaces = await createWorkspaces({ store, dbPath, provision }), workspace = await workspaces.create({ name: '공지 테스트', guildId });
    const db = (await workspaces.open(workspace.id)).db;
    await store.db.prepare("UPDATE lms_discord_jobs SET state='succeeded',completed_at=1,results=? WHERE guild_id=?").run(JSON.stringify([{ id: 'notice', discordId: channelId, action: 'created' }]), guildId);
    const put = async (kind, value) => await (db.prepare('INSERT INTO lms_records VALUES(?,?,?)')).run(kind, value.id, JSON.stringify(value));
    await put('courses', { id: 'c1', title: '과정' });
    await put('notices', { id: 'n1', courseId: 'c1', title: '공지', content: '@everyone 안내', target: '과정 전체', status: '초안' });
    let clock = 1000;
    const outbox = createOutbox(store.db, workspaces, { now: () => clock });
    const read = async () => (await outbox.notices(workspace.id, admin)).notices[0];
    const send = async () => await outbox.enqueueNotice(workspace.id, 'n1', { revision: (await read()).revision }, admin);
    const poll = async () => (await outbox.poll({ guildIds: [guildId] })).job;
    const complete = async (job, state = 'sent', error = '', msg = messageId) => await outbox.complete({ workspaceId: workspace.id, id: job.id, claim: job.claim, state, error, messageId: msg });
    t.after(() => { workspaces.close(); store.db.close(); rmSync(dir, { recursive: true, force: true }); });
    return { db, store, workspaces, workspace, outbox, read, send, poll, complete, advance: () => { clock += 120001; } };
}
test('one immutable notice delivery survives repeated requests and records a claimed result', async (t) => {
    const f = await fixture(t);
    await f.send();
    await f.send();
    assert.equal((await (f.db.prepare('SELECT COUNT(*) AS n FROM lms_outbox')).get()).n, 1);
    const job = await f.poll();
    assert.ok(job);
    assert.equal(await f.poll(), null);
    assert.equal(job.channelId, channelId);
    assert.equal(job.reconcile, false);
    await assert.rejects(async () => await f.workspaces.mutate(f.workspace.id, { revision: (await f.workspaces.snapshot(f.workspace.id)).revision, changes: [{ kind: 'notices', value: { id: 'n1', courseId: 'c1', title: '수정', content: '수정', target: '과정 전체', status: '초안' } }] }, 'operator'), { status: 409 });
    await f.complete(job);
    assert.equal((await f.read()).delivery.messageId, messageId);
    await assert.rejects(async () => await f.complete(job), { status: 409 });
    assert.equal((await f.read()).attempts.length, 2);
});

test('availability notifications wait for a capable bot and failed retry keeps its DM destination', async t => {
    const f = await fixture(t);
    await f.db.prepare('INSERT INTO lms_outbox(id,event_key,kind,source_id,guild_id,channel_id,payload,actor,created_at) VALUES(?,?,?,?,?,?,?,?,?)')
        .run('availability-1', 'availability:user', 'mentor_availability', 'user', guildId, `dm:${messageId}`, JSON.stringify({ title: '입력', description: '시간 입력', audience: 'individual', targetId: messageId }), 'scheduler', 1000);
    assert.equal(await f.poll(), null);
    const poll = async () => (await f.outbox.poll({ guildIds: [guildId], capabilities: ['mentor_availability'] })).job;
    const job = await poll();
    assert.equal(job.kind, 'mentor_availability');
    await f.complete(job, 'failed', 'permissions', '');
    await f.outbox.retry(f.workspace.id, job.id, admin);
    assert.equal((await poll()).channelId, `dm:${messageId}`);
});
test('lost completion and restart reconcile the original channel, never blindly resend', async (t) => {
    const f = await fixture(t);
    await f.send();
    const first = await f.poll();
    f.advance();
    const recovered = await f.poll();
    assert.equal(recovered.id, first.id);
    assert.equal(recovered.nonce, first.nonce);
    assert.equal(recovered.reconcile, true);
    await assert.rejects(async () => await f.complete(first), { status: 409 });
    await f.complete(recovered, 'uncertain', 'not_found', '');
    assert.equal(await f.poll(), null);
    await f.outbox.retry(f.workspace.id, first.id, admin);
    const checked = await f.poll();
    assert.equal(checked.reconcile, true);
    await f.complete(checked);
    assert.equal((await f.read()).delivery.state, 'sent');
});
test('known failure can retry; manual delivery must first hold the queue and validate channel evidence', async (t) => {
    const f = await fixture(t);
    await f.send();
    const job = await f.poll();
    await assert.rejects(async () => await f.outbox.hold(f.workspace.id, job.id, admin), { status: 409 });
    await f.complete(job, 'failed', 'permissions', '');
    await f.outbox.retry(f.workspace.id, job.id, admin);
    assert.equal((await f.read()).delivery.state, 'pending');
    await f.outbox.hold(f.workspace.id, job.id, admin);
    assert.equal(await f.poll(), null);
    await assert.rejects(async () => await f.outbox.manual(f.workspace.id, job.id, { messageUrl: `https://discord.com/channels/${guildId}/${messageId}/${messageId}` }, admin), { status: 422 });
    await f.outbox.manual(f.workspace.id, job.id, { messageUrl: `https://discord.com/channels/${guildId}/${channelId}/${messageId}` }, admin);
    assert.equal((await f.read()).delivery.state, 'manual');
    assert.equal(await f.poll(), null);
});
test('scope, stale previews, private targets, archive and arbitrary destination inputs fail closed', async (t) => {
    const f = await fixture(t);
    await assert.rejects(async () => await f.outbox.notices(f.workspace.id, { id: 'foreign', role: 'student' }), { status: 403 });
    await assert.rejects(async () => await f.outbox.enqueueNotice(f.workspace.id, 'n1', { revision: 'stale' }, admin), { status: 409 });
    await assert.rejects(async () => await f.outbox.enqueueNotice(f.workspace.id, 'n1', { revision: (await f.read()).revision, channelId }, admin));
    await (f.db.prepare("UPDATE lms_records SET data=json_set(data,'$.target','관리자') WHERE kind='notices'")).run();
    await assert.rejects(async () => await f.send(), { status: 422 });
    await (f.db.prepare("UPDATE lms_records SET data=json_set(data,'$.target','과정 전체') WHERE kind='notices'")).run();
    await f.send();
    await f.workspaces.setArchived(f.workspace.id, true, admin);
    assert.equal(await f.poll(), null);
    await assert.rejects(async () => await f.send(), { status: 409 });
});
