import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createStore } from './store.mjs';
import { createAuth } from './auth.mjs';
import { createRenderSync } from './render-sync.mjs';
import { createProvision } from './provision.mjs';
import { createWorkspaces } from './workspaces.mjs';
import { createAdmissions } from './admissions.mjs';
import { createOnboarding } from './onboarding.mjs';
import { createStaffFlow } from './staff-flow.mjs';
const admin = { id: 'admin', username: 'admin', role: 'admin' };
const guildId = '555456789012345678', discordId = '655456789012345678';
const secret = 'test-only-token-12345678901234567890';
async function fixture(t) {
    const folder = mkdtempSync(join(tmpdir(), 'staff-flow-')), dbPath = join(folder, 'main.db');
    let currentTime = Date.now();
    const store = await createStore(dbPath), auth = await createAuth(store.db, { botToken: secret, guildAllowed: () => true, now: () => currentTime });
    await createRenderSync(store.db);
    const provision = await createProvision(store.db, { token: secret });
    const workspaces = await createWorkspaces({ store, dbPath, provision });
    const admissions = await createAdmissions(store.db, workspaces, { token: secret });
    const onboarding = await createOnboarding(store.db, workspaces, provision);
    const staff = await createStaffFlow(store.db, workspaces, onboarding, admissions);
    const workspace = await workspaces.create({ name: '멘토 운영' });
    const signup = async (username, role = 'instructor', scope = {}, actor = admin) => {
        const invitation = await workspaces.invite(workspace.id, { username, role, ...scope }, actor);
        const { user } = await auth.signup({ username, name: username, password: 'test-staff-password-1234' }, () => { });
        await workspaces.acceptInvitation(invitation.token, user);
        return user;
    };
    const verify = async (user, targetGuild = guildId) => {
        currentTime += 61000;
        const challenge = await auth.issueVerification(user, targetGuild);
        await auth.verify({ code: challenge.code, discordId, guildId: targetGuild });
    };
    const setup = async (count) => await staff.setupGroups(workspace.id, { count, revision: (await staff.groups(workspace.id)).revision }, admin);
    const connect = async () => { await workspaces.addServer(workspace.id, { guildId, templateRevision: (await workspaces.template(workspace.id)).revision }); await staff.enableTeams(workspace.id); };
    t.after(() => { workspaces.close(); store.db.close(); rmSync(folder, { recursive: true, force: true }); });
    return { store, auth, workspaces, workspace, staff, admissions, onboarding, signup, setup, connect, verify };
}
test('workspace administrator joins before a Discord server exists and invites scoped mentors without platform privileges', async (t) => {
    const { workspaces, workspace, signup, setup } = await fixture(t);
    const owner = await signup('workspace.owner', 'admin');
    assert.equal(owner.verified, false);
    assert.equal(owner.role, 'student');
    assert.equal(await workspaces.role(workspace.id, owner), 'admin');
    assert.deepEqual((await workspaces.metadata(workspace.id)).guildIds, []);
    await assert.rejects(async () => await workspaces.invite(workspace.id, { username: 'new.admin', role: 'admin' }, owner), { status: 403 });
    const groups = await setup(3);
    const mentor = await signup('group.mentor', 'instructor', { mentorType: 'group', teamIds: [groups.teams[0].id] }, owner);
    assert.equal(await workspaces.role(workspace.id, mentor), 'instructor');
    await assert.rejects(async () => await workspaces.requireRole(workspace.id, mentor, ['admin']), { status: 403 });
    await assert.rejects(async () => await workspaces.requireAccess('default', mentor), { status: 403 });
});
test('group count creates durable teams, survives retries, enables the bound server, and never removes existing teams', async (t) => {
    const { store, staff, workspace, setup, connect, onboarding } = await fixture(t);
    const first = await setup(3), ids = first.teams.map(t => t.id);
    assert.deepEqual((await setup(3)).teams.map(t => t.id), ids);
    await store.db.prepare('DELETE FROM lms_group_setup WHERE workspace_id=?').run(workspace.id);
    assert.deepEqual((await setup(3)).teams.map(t => t.id), ids);
    assert.equal((await staff.groups(workspace.id)).courses.length, 1);
    assert.equal((await setup(5)).teams.length, 5);
    await assert.rejects(async () => await setup(2), { status: 409 });
    await assert.rejects(async () => await staff.setupGroups(workspace.id, { count: 6, revision: first.revision }, admin), { status: 409 });
    await connect();
    const cfg = (await onboarding.poll({ guildIds: [guildId] })).configs[0];
    assert.equal(cfg.enabled, true);
    assert.equal(cfg.teams.length, 5);
    assert.equal(cfg.courseIds[0], first.courseId);
});
test('mentor profile queues only their guild invite, verified identity registers one mentor, and ordered guide progress persists', async (t) => {
    const { store, staff, workspace, workspaces, auth, admissions, onboarding, signup, setup, connect } = await fixture(t);
    await setup(2);
    await connect();
    const user = await signup('main.mentor');
    await assert.rejects(async () => await staff.invite(workspace.id, user), { status: 422 });
    const result = await staff.profile(workspace.id, { name: '강사', expertise: 'AI', bio: '자기소개' }, user);
    assert.equal(result.invitation.inviteState, 'queued');
    assert.equal((await admissions.reviewList(workspace.id, admin)).applications.length, 0);
    assert.equal((await admissions.poll({ guildIds: ['755456789012345678'] })).job, null);
    const { job } = await admissions.poll({ guildIds: [guildId] });
    assert.equal(job.guildId, guildId);
    await admissions.complete({ id: job.id, claim: job.claim, success: true, code: 'MentorTest' });
    assert.equal((await staff.read(workspace.id, user)).invitation.inviteUrl, 'https://discord.gg/MentorTest');
    await assert.rejects(async () => await staff.step(workspace.id, { step: 'assignments' }, user), { status: 409 });
    assert.equal((await staff.read(workspace.id, user)).completed, false);
    const verification = await auth.issueVerification(user, guildId);
    await auth.verify({ code: verification.code, discordId, guildId });
    await admissions.activate(discordId, guildId);
    await staff.syncDiscord(discordId, guildId);
    await staff.syncDiscord(discordId, guildId);
    assert.equal((await ((await workspaces.open(workspace.id)).db.prepare('SELECT COUNT(*) AS n FROM mentors')).get()).n, 1);
    assert.equal(await workspaces.role(workspace.id, user), 'instructor');
    assert.equal((await onboarding.poll({ guildIds: [guildId] })).configs[0].participants[0].name, '강사');
    const updated = await staff.profile(workspace.id, { name: '변경된 활동명', expertise: 'AI' }, user);
    assert.equal(updated.profile.bio, '자기소개');
    assert.equal((await onboarding.poll({ guildIds: [guildId] })).configs[0].participants[0].name, '변경된 활동명');
    assert.equal((await staff.read(workspace.id, user)).verified, true);
    await assert.rejects(async () => await staff.step(workspace.id, { step: 'mentoring' }, user), { status: 409 });
    for (const step of ['assignments', 'approval', 'mentoring', 'mentoring'])
        await staff.step(workspace.id, { step }, user);
    assert.equal((await staff.read(workspace.id, user)).completed, true);
    assert.equal((await staff.read(workspace.id, user)).profile.steps.length, 3);
    await store.db.prepare('UPDATE lms_users SET guild_id=? WHERE id=?').run('755456789012345678', user.id);
    assert.equal((await staff.read(workspace.id, user)).verified, true);
});
test('changing mentor teams changes bot roles and LMS scope; foreign teams and out-of-scope edits are rejected', async (t) => {
    const { workspace, workspaces, onboarding, signup, setup, connect, verify } = await fixture(t);
    const { teams, courseId } = await setup(2);
    await connect();
    const user = await signup('scoped.mentor', 'instructor', { mentorType: 'group', teamIds: [teams[0].id] });
    await verify(user);
    const write = async (changes) => await workspaces.mutate(workspace.id, { revision: (await workspaces.snapshot(workspace.id)).revision, changes }, 'test');
    for (const [index, team] of await teams.entries())
        await write([{ kind: 'learners', value: { id: `l${index}`, name: '학습자', email: `l${index}@example.com`, courseId, team: team.name, status: '정상', discordId: '' } }]);
    assert.deepEqual((await workspaces.teaching(workspace.id, user)).learners.map(l => l.id), ['l0']);
    const before = (await onboarding.poll({ guildIds: [guildId] })).configs[0];
    assert.deepEqual(before.participants[0].teamIds, [teams[0].id]);
    await assert.rejects(async () => await workspaces.assignMentor(workspace.id, user.id, { mentorType: 'group', teamIds: ['foreign'] }, admin), { status: 422 });
    await assert.rejects(async () => await workspaces.assignMentor(workspace.id, user.id, { mentorType: 'main' }, user), { status: 403 });
    const score = { id: 'score', studentId: 'l1', courseId, item: '과제', score: 5, maximum: 10 };
    await assert.rejects(async () => await workspaces.teach(workspace.id, { revision: (await workspaces.snapshot(workspace.id)).revision, changes: [{ kind: 'scores', value: score }] }, user), { status: 403 });
    await workspaces.assignMentor(workspace.id, user.id, { mentorType: 'group', teamIds: [teams[1].id] }, admin);
    const after = (await onboarding.poll({ guildIds: [guildId] })).configs[0];
    assert.notEqual(after.revision, before.revision);
    assert.deepEqual(after.participants[0].teamIds, [teams[1].id]);
    assert.deepEqual((await workspaces.teaching(workspace.id, user)).learners.map(l => l.id), ['l1']);
    await workspaces.teach(workspace.id, { revision: (await workspaces.snapshot(workspace.id)).revision, changes: [{ kind: 'scores', value: score }] }, user);
    await workspaces.assignMentor(workspace.id, user.id, { mentorType: 'main', teamIds: [] }, admin);
    assert.equal((await workspaces.teaching(workspace.id, user)).learners.length, 2);
    assert.equal((await onboarding.poll({ guildIds: [guildId] })).configs[0].participants[0].teamIds.length, 2);
});
test('member editing is workspace scoped, updates mentor identity, and prevents administrator escalation', async (t) => {
    const { store, staff, workspace, workspaces, signup, setup, connect, verify } = await fixture(t);
    const { teams } = await setup(2);
    await connect();
    const owner = await signup('edit.owner', 'admin'), mentor = await signup('edit.mentor');
    await staff.profile(workspace.id, { name: '인증 전', expertise: 'AI' }, mentor);
    await verify(mentor);
    await staff.profile(workspace.id, { name: '기존 활동명', expertise: 'AI' }, mentor);
    const other = await workspaces.create({ name: '다른 워크스페이스', guildId: '755456789012345678' });
    await workspaces.acceptInvitation((await workspaces.invite(other.id, { username: mentor.username, role: 'instructor' }, admin)).token, mentor);
    await verify(mentor, '755456789012345678');
    await staff.profile(other.id, { name: '다른 활동명', expertise: '개발' }, mentor);
    const update = { name: '수정된 활동명', expertise: '데이터', role: 'instructor', mentorType: 'group', teamIds: [teams[1].id] };
    await assert.rejects(async () => await staff.editMember(workspace.id, mentor.id, { ...update, role: 'admin' }, owner), { status: 403 });
    await assert.rejects(async () => await staff.editMember(workspace.id, owner.id, update, owner), { status: 403 });
    await assert.rejects(async () => await staff.editMember(workspace.id, mentor.id, { ...update, teamIds: ['foreign'] }, owner), { status: 422 });
    await assert.rejects(async () => await staff.editMember(workspace.id, mentor.id, update, mentor), { status: 403 });
    await assert.rejects(async () => await staff.editMember(other.id, mentor.id, update, owner), { status: 403 });
    const result = await staff.editMember(workspace.id, mentor.id, update, owner);
    assert.equal(result.members.find(m => m.id === mentor.id).name, update.name);
    assert.deepEqual((await workspaces.mentorScope(workspace.id, mentor.id)).teamIds, [teams[1].id]);
    assert.equal((await workspaces.snapshot(workspace.id)).mentors[0].name, update.name);
    assert.equal((await workspaces.snapshot(other.id)).mentors[0].name, '다른 활동명');
    assert.equal((await store.db.prepare('SELECT name FROM lms_users WHERE id=?').get(mentor.id)).name, mentor.name);
    assert.equal((await store.db.prepare("SELECT COUNT(*) AS n FROM lms_audit WHERE action='member.update'").get()).n, 1);
    await staff.editMember(workspace.id, owner.id, { ...update, role: 'admin' }, admin);
    assert.equal((await staff.members(workspace.id, admin)).members.find(m => m.id === owner.id).name, update.name);
});
test('removal revokes only one membership and pending staff invites, preserves history, and closes booking access', async (t) => {
    const { store, staff, workspace, workspaces, signup, setup, connect, admissions, onboarding, verify } = await fixture(t);
    await setup(1);
    await connect();
    const owner = await signup('remove.owner', 'admin'), mentor = await signup('remove.mentor');
    await staff.profile(workspace.id, { name: '인증 전', expertise: 'AI' }, mentor);
    await verify(mentor);
    await staff.profile(workspace.id, { name: '멘토', expertise: '개발' }, mentor);
    const other = await workspaces.create({ name: '별도 운영', guildId: '755456789012345678' });
    await workspaces.acceptInvitation((await workspaces.invite(other.id, { username: mentor.username, role: 'instructor' }, admin)).token, mentor);
    await verify(mentor, '755456789012345678');
    await staff.profile(other.id, { name: '별도 멘토', expertise: '개발' }, mentor);
    const target = (await workspaces.open(workspace.id)).db, mentorId = (await (target.prepare('SELECT id FROM mentors')).get()).id;
    await (target.prepare("INSERT INTO slots(mentor_id,start_time,end_time,label) VALUES(?,'2030-01-01T12:00:00','2030-01-01T13:00:00','보존할 예약')")).run(mentorId);
    await (target.prepare("INSERT INTO bookings(slot_id,user_id,user_name,status) VALUES(1,'student','학생','approved')")).run();
    const { job } = await admissions.poll({ guildIds: [guildId] });
    assert.ok(job);
    await assert.rejects(async () => await staff.removeMember(workspace.id, owner.id, owner), { status: 403 });
    await assert.rejects(async () => await staff.removeMember(workspace.id, mentor.id, mentor), { status: 403 });
    await staff.removeMember(workspace.id, mentor.id, owner);
    await assert.rejects(async () => await workspaces.requireAccess(workspace.id, mentor), { status: 403 });
    await assert.rejects(async () => await staff.profile(workspace.id, { name: '다시', expertise: 'AI' }, mentor), { status: 403 });
    await assert.rejects(async () => await staff.removeMember(workspace.id, mentor.id, owner), { status: 404 });
    assert.equal(await workspaces.role(other.id, mentor), 'instructor');
    assert.equal((await workspaces.snapshot(other.id)).mentors.length, 1);
    assert.equal((await (target.prepare('SELECT COUNT(*) AS n FROM bookings')).get()).n, 1);
    assert.equal((await (target.prepare('SELECT is_active FROM mentors')).get()).is_active, 0);
    assert.equal((await (target.prepare('SELECT is_active FROM slots')).get()).is_active, 0);
    assert.equal((await workspaces.snapshot(workspace.id)).mentors.length, 0);
    assert.equal((await workspaces.snapshot(workspace.id)).sessions.length, 1);
    assert.equal((await onboarding.poll({ guildIds: [guildId] })).configs[0].participants.some(p => p.discordId === discordId), false);
    await assert.rejects(async () => await admissions.complete({ id: job.id, claim: job.claim, success: true, code: 'StaleInvite' }), { status: 409 });
    assert.equal((await staff.members(workspace.id, owner)).members.some(m => m.id === mentor.id), false);
    await staff.removeMember(workspace.id, owner.id, admin);
    assert.equal(await workspaces.role(workspace.id, owner), null);
    assert.ok(await store.db.prepare('SELECT id FROM lms_users WHERE id=?').get(owner.id));
    const fresh = await workspaces.invite(workspace.id, { username: mentor.username, role: 'instructor' }, admin);
    await workspaces.acceptInvitation(fresh.token, mentor);
    await staff.profile(workspace.id, { name: '재초대 멘토', expertise: 'AI' }, mentor);
    assert.equal((await (target.prepare('SELECT COUNT(*) AS n FROM mentors')).get()).n, 1);
    assert.equal((await (target.prepare('SELECT is_active FROM mentors')).get()).is_active, 0);
    await verify(mentor);
    await staff.syncDiscord(discordId, guildId);
    assert.equal((await (target.prepare('SELECT is_active FROM mentors')).get()).is_active, 1);
    assert.equal((await (target.prepare('SELECT is_active FROM slots')).get()).is_active, 0);
});
test('pending invitations can change scope and role with the same token, but cannot bypass administrator boundaries', async (t) => {
    const { workspaces, workspace, signup, setup, auth } = await fixture(t);
    const owner = await signup('invite.owner', 'admin'), { teams } = await setup(2);
    const invitation = await workspaces.invite(workspace.id, { username: 'invite.mentor', role: 'instructor' }, owner);
    const input = { role: 'instructor', mentorType: 'group', teamIds: [teams[1].id] };
    await workspaces.editInvitation(workspace.id, invitation.id, input, owner);
    assert.deepEqual((await workspaces.previewInvitation(invitation.token)).teamIds, input.teamIds);
    await assert.rejects(async () => await workspaces.editInvitation(workspace.id, invitation.id, { ...input, role: 'admin' }, owner), { status: 403 });
    await workspaces.editInvitation(workspace.id, invitation.id, { role: 'admin' }, admin);
    await assert.rejects(async () => await workspaces.editInvitation(workspace.id, invitation.id, input, owner), { status: 403 });
    await assert.rejects(async () => await workspaces.invite(workspace.id, { username: 'invite.mentor', role: 'instructor' }, owner), { status: 403 });
    await assert.rejects(async () => await workspaces.revokeInvitation(workspace.id, invitation.id, owner), { status: 403 });
    await workspaces.editInvitation(workspace.id, invitation.id, input, admin);
    const { user } = await auth.signup({ username: 'invite.mentor', name: '멘토', password: 'test-staff-password-1234' }, () => { });
    await workspaces.acceptInvitation(invitation.token, user);
    assert.deepEqual((await workspaces.mentorScope(workspace.id, user.id)).teamIds, input.teamIds);
    await assert.rejects(async () => await workspaces.editInvitation(workspace.id, invitation.id, input, owner), { status: 409 });
    const cancelled = await workspaces.invite(workspace.id, { username: 'cancel.mentor', role: 'instructor' }, owner);
    await workspaces.revokeInvitation(workspace.id, cancelled.id, owner);
    await assert.rejects(async () => await workspaces.editInvitation(workspace.id, cancelled.id, input, owner), { status: 409 });
});
test('default workspace member edits and removal use a single transaction on the shared registry database', async (t) => {
    const { staff, workspaces, auth } = await fixture(t);
    const invitation = await workspaces.invite('default', { username: 'default.mentor', role: 'instructor' }, admin);
    const { user } = await auth.signup({ username: 'default.mentor', name: '기본 멘토', password: 'test-staff-password-1234' }, () => { });
    await workspaces.acceptInvitation(invitation.token, user);
    await staff.editMember('default', user.id, { name: '수정', expertise: '', role: 'instructor' }, admin);
    assert.equal((await staff.members('default', admin)).members.find(m => m.id === user.id).name, '수정');
    await staff.removeMember('default', user.id, admin);
    assert.equal(await workspaces.role('default', user), null);
});
