import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createStore } from './store.mjs';
import { createAuth } from './auth.mjs';
import { createRenderSync } from './render-sync.mjs';
import { createProvision } from './provision.mjs';
import { createWorkspaces } from './workspaces.mjs';
import { createAdmissions } from './admissions.mjs';
import { createOnboarding } from './onboarding.mjs';
import { createStaffFlow } from './staff-flow.mjs';
import { migrateVerification, workspaceVerified } from './workspace-verification.mjs';
import { studentLearning } from './student.mjs';
const admin = { id: 'admin', role: 'admin', username: 'admin' };
const guildA = '111456789012345678', guildB = '222456789012345678', discordId = '333456789012345678';
const token = 'test-only-workspace-auth-token-1234567890';
async function fixture(t) {
    const folder = mkdtempSync(join(tmpdir(), 'workspace-verification-')), dbPath = join(folder, 'main.db');
    let time = Date.now();
    const store = await createStore(dbPath), db = store.db;
    const auth = await createAuth(db, { adminPassword: 'test-platform-setup-key-1234', botToken: token, guildAllowed: () => true, now: () => time });
    await createRenderSync(db);
    const provision = await createProvision(db, { token });
    const workspaces = await createWorkspaces({ store, dbPath, provision });
    const admissions = await createAdmissions(db, workspaces, { token });
    const onboarding = await createOnboarding(db, workspaces, provision);
    const staff = await createStaffFlow(db, workspaces, onboarding, admissions);
    const a = await workspaces.create({ name: '인증 A', guildId: guildA }), b = await workspaces.create({ name: '인증 B', guildId: guildB });
    for (const w of [a, b])
        await staff.setupGroups(w.id, { count: 1, revision: (await staff.groups(w.id)).revision }, admin);
    const signup = async () => (await auth.signup({ username: 'separate.user', name: '사용자', password: 'test-password-1234' }, () => { })).user;
    const invite = async (w, user) => await workspaces.acceptInvitation((await workspaces.invite(w.id, { username: user.username, role: 'instructor' }, admin)).token, user);
    const verify = async (challenge, guildId) => await auth.verify({ code: challenge.code, discordId, guildId });
    const participants = async (guildId) => (await onboarding.poll({ guildIds: [guildId] })).configs[0].participants;
    t.after(() => { workspaces.close(); db.close(); rmSync(folder, { recursive: true, force: true }); });
    return { db, auth, workspaces, admissions, onboarding, staff, a, b, signup, invite, verify, participants, advance: () => { time += 61000; } };
}
test('concurrent workspace codes are independent; verifying A cannot register a mentor or grant roles in B', async (t) => {
    const { auth, workspaces, staff, a, b, signup, invite, verify, participants } = await fixture(t);
    const user = await signup();
    for (const w of [a, b]) {
        await invite(w, user);
        await staff.profile(w.id, { name: w.name, expertise: 'AI' }, user);
    }
    const first = await auth.issueVerification(user, guildA), second = await auth.issueVerification(user, guildB);
    await assert.rejects(async () => await verify(first, guildB), { status: 403 });
    await verify(first, guildA);
    await staff.syncDiscord(discordId, guildA);
    assert.equal((await auth.status(second.ticket)).state, 'pending');
    assert.equal((await staff.read(a.id, user)).verified, true);
    assert.equal((await staff.read(b.id, user)).verified, false);
    await staff.profile(b.id, { name: 'B 강사', expertise: 'AI' }, user);
    await staff.syncDiscord(discordId, guildB); // A callback alone cannot create proof.
    assert.equal((await workspaces.snapshot(b.id)).mentors.length, 0);
    assert.equal((await participants(guildA)).length, 1);
    assert.equal((await participants(guildB)).length, 0);
    assert.equal((await workspaces.list(user)).find(w => w.id === b.id).discordVerified, false);
    await verify(second, guildB);
    await staff.syncDiscord(discordId, guildB);
    assert.equal((await staff.read(a.id, user)).verified, true);
    assert.equal((await staff.read(b.id, user)).verified, true);
    assert.equal((await participants(guildB)).length, 1);
    assert.equal((await workspaces.snapshot(b.id)).mentors[0].name, 'B 강사');
    assert.ok((await workspaces.list(user)).every(w => w.discordVerified));
});
test('renewal replaces only its workspace code; removal revokes only that proof and its pending tickets', async (t) => {
    const { auth, workspaces, staff, a, b, signup, invite, verify, advance } = await fixture(t);
    const user = await signup();
    await invite(a, user);
    await invite(b, user);
    const first = await auth.issueVerification(user, guildA), second = await auth.issueVerification(user, guildB);
    advance();
    const renewed = await auth.renew(first.ticket);
    await assert.rejects(async () => await verify(first, guildA), { status: 410 });
    await verify(renewed, guildA);
    await verify(second, guildB);
    advance();
    const pending = await auth.issueVerification(user, guildA);
    await staff.removeMember(a.id, user.id, admin);
    assert.equal((await workspaces.list(user)).find(w => w.id === b.id).discordVerified, true);
    await assert.rejects(async () => await verify(pending, guildA), { status: 410 });
    await assert.rejects(async () => await auth.renew(pending.ticket), { status: 404 });
    await assert.rejects(async () => await auth.issueVerification(user, guildA), { status: 403 });
    await invite(a, user);
    assert.equal((await staff.read(a.id, user)).verified, false);
});
test('student approval and activation remain independent in two workspaces', async (t) => {
    const { db, auth, workspaces, admissions, staff, a, b, signup, verify, participants } = await fixture(t);
    const user = await signup();
    for (const w of [a, b]) {
        const application = await admissions.apply(w.id, user);
        await admissions.review(w.id, application.id, { action: 'approve', guildId: w.guildIds[0], teamId: (await staff.groups(w.id)).teams[0].id }, admin);
    }
    const first = await auth.issueVerification(user, guildA), second = await auth.issueVerification(user, guildB);
    await verify(first, guildA);
    await admissions.activate(discordId, guildA);
    await admissions.activate(discordId, guildB);
    assert.equal(await workspaces.role(a.id, user), 'student');
    assert.equal(await workspaces.role(b.id, user), null);
    assert.equal((await admissions.own(user)).find(a => a.workspaceId === b.id).state, 'approved');
    assert.equal((await participants(guildB)).length, 0);
    await verify(second, guildB);
    await admissions.activate(discordId, guildB);
    assert.equal(await workspaces.role(b.id, user), 'student');
    assert.equal((await participants(guildA)).length, 1);
    assert.equal((await participants(guildB)).length, 1);
    assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM lms_workspace_verifications WHERE user_id=?').get(user.id)).n, 2);
    await db.prepare('DELETE FROM lms_workspace_verifications WHERE workspace_id=?').run(b.id);
    const account = { ...user, discordId, verified: true };
    assert.equal((await studentLearning((await workspaces.open(a.id)).db, account, (await workspaces.requireAccess(a.id, user)).discordVerified)).courses.length, 1);
    assert.equal((await studentLearning((await workspaces.open(b.id)).db, account, (await workspaces.requireAccess(b.id, user)).discordVerified)).courses.length, 0);
});
test('migration preserves only recorded guild proofs, including earlier staff and student verifications, and never resurrects revoked proof', async (t) => {
    const { db, workspaces, admissions, a, b, signup, invite } = await fixture(t);
    const user = await signup();
    await invite(a, user);
    await invite(b, user);
    const c = await workspaces.create({ name: '이전 수강', guildId: '444456789012345678' });
    const d = await workspaces.create({ name: '미인증', guildId: '555456789012345678' });
    await invite(d, user);
    const application = await admissions.apply(c.id, user);
    await db.prepare("UPDATE lms_admissions SET state='joined',guild_id=? WHERE id=?").run(c.guildIds[0], application.id);
    await db.prepare('UPDATE lms_users SET discord_id=?,guild_id=?,verified_at=1 WHERE id=?').run(discordId, guildA, user.id);
    await db.prepare('INSERT INTO lms_staff_connections VALUES(?,?,?)').run(b.id, user.id, discordId);
    await db.prepare("DELETE FROM lms_workspace_migrations WHERE name='verification-v1'").run();
    await migrateVerification(db);
    for (const w of [a, b, c])
        assert.equal(await workspaceVerified(db, w.id, user.id), true);
    assert.equal(await workspaceVerified(db, d.id, user.id), false);
    await db.prepare('DELETE FROM lms_workspace_verifications WHERE workspace_id=?').run(a.id);
    await migrateVerification(db);
    assert.equal(await workspaceVerified(db, a.id, user.id), false);
});
test('workspace archive and guild reassignment invalidate issued codes without producing a proof', async (t) => {
    const { db, auth, workspaces, a, b, signup, invite, verify } = await fixture(t);
    const user = await signup();
    await invite(a, user);
    await invite(b, user);
    const first = await auth.issueVerification(user, guildA), second = await auth.issueVerification(user, guildB);
    await workspaces.setArchived(a.id, true, admin);
    await assert.rejects(async () => await verify(first, guildA), { status: 403 });
    const other = await workspaces.create({ name: '서버 재연결 대상' });
    await db.prepare('UPDATE lms_workspace_guilds SET workspace_id=? WHERE guild_id=?').run(other.id, guildB);
    await assert.rejects(async () => await verify(second, guildB), { status: 403 });
    assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM lms_workspace_verifications').get()).n, 0);
});
test('a personal platform administrator links once and cannot switch identity or reuse another workspace proof', async (t) => {
    const { auth, db, workspaces, a, b, advance } = await fixture(t);
    const { user } = await auth.setup({ username: 'platform.owner', name: '총괄 관리자', password: 'test-password-1234', setupKey: 'test-platform-setup-key-1234' });
    const first = await auth.issueVerification(user, guildA);
    await assert.rejects(async () => await auth.verify({ code: first.code, discordId, guildId: guildB }), { status: 403 });
    assert.equal((await auth.preview({ code: first.code, discordId, guildId: guildA })).username, user.username);
    await auth.verify({ code: first.code, discordId, guildId: guildA });
    assert.equal((await workspaces.requireAccess(a.id, user)).discordVerified, true);
    assert.equal((await workspaces.requireAccess(b.id, user)).discordVerified, false);
    const second = await auth.issueVerification(user, guildB);
    await assert.rejects(async () => await auth.verify({ code: second.code, discordId: '999456789012345678', guildId: guildB }), { status: 403 });
    await assert.rejects(async () => await auth.verify({ code: first.code, discordId, guildId: guildA }), { status: 410 });
    advance();
    await workspaces.setArchived(b.id, true, admin);
    await assert.rejects(async () => await auth.verify({ code: second.code, discordId, guildId: guildB }), { status: 403 });
    assert.equal((await db.prepare('SELECT discord_id FROM lms_users WHERE id=?').get(user.id)).discord_id, discordId);
});
