import { useState } from 'react'
import { ArrowRight, ArrowUpRight, BookOpen, Bot, CalendarDays, ChevronLeft, ChevronRight, ClipboardList, MessageSquare, Users } from 'lucide-react'
import { Badge, CardHeading, CourseCard, Empty } from './components'
import type { Course, Workspace } from './data'

function dateKey(value: Date) { return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-${String(value.getDate()).padStart(2, '0')}` }
function addDays(value: Date, days: number) { const result = new Date(value); result.setDate(result.getDate() + days); return result }
export default function Dashboard({ data, query, go, selectCourse, addSession }: { data: Workspace; query: string; go: (page: string) => void; selectCourse: (course: Course) => void; addSession: () => void }) {
  const [today] = useState(() => data.mode === 'demo' ? new Date(2026, 8, 15) : new Date())
  const [selected, setSelected] = useState(dateKey(today))
  const [weekOffset, setWeekOffset] = useState(0)
  const [period, setPeriod] = useState('이번 주')
  const monday = addDays(today, -((today.getDay() + 6) % 7))
  const days = Array.from({ length: 7 }, (_, i) => addDays(monday, weekOffset * 7 + i))
  const pending = data.sessions.filter(s => s.status === '승인 대기').length
  const courses = data.courses.filter(c => `${c.title} ${c.mentor}`.toLowerCase().includes(query.toLowerCase()))
  const chartDays = Array.from({ length: 7 }, (_, i) => dateKey(addDays(monday, i - (period === '지난 주' ? 7 : 0))))
  const attendance = data.attendance.filter(a => chartDays.includes(String(a.date)))
  const values = chartDays.map(day => { const rows = attendance.filter(a => a.date === day); return rows.length ? Math.round(rows.filter(a => a.status === '출석' || a.status === '공결').length / rows.length * 100) : 0 })
  const rate = attendance.length ? Math.round(attendance.filter(a => a.status === '출석' || a.status === '공결').length / attendance.length * 100) : 0
  const learnerCount = data.mode === 'demo' ? data.courses.reduce((sum, c) => sum + c.learners, 0) : data.learners.length
  const sessions = data.sessions.filter(s => s.date === selected && s.status !== '취소').sort((a, b) => a.time.localeCompare(b.time))
  return <>
    <section className="welcome-banner operations-banner"><div><span className="welcome-kicker"><span className="live-dot" /> AX 학습관리시스템 · LEARNING OPERATIONS</span><h2>{data.name}</h2><p>과정 · 수강생 · 출결 · 성적 · 과제 · 멘토링</p><button onClick={() => go('bots')}>연동 상태 확인 <ArrowRight size={16} /></button></div><div className="banner-metrics"><div><span>운영 과정</span><strong>{data.courses.filter(c => c.status === '진행 중').length}<small>개</small></strong></div><div><span>수강생</span><strong>{learnerCount}<small>명</small></strong></div><div><span>승인 대기</span><strong>{pending}<small>건</small></strong></div></div></section>
    <section className="stats-grid" aria-label="운영 통계">{[
      { label: '전체 수강생', value: learnerCount, unit: '명', icon: Users, color: 'sage', detail: '등록된 수강생', page: 'learners' },
      { label: '등록 과정', value: data.courses.length, unit: '개', icon: BookOpen, color: 'peach', detail: '준비 · 운영 · 종료 과정', page: 'courses' },
      { label: '이번 주 멘토링', value: data.sessions.filter(s => s.date >= dateKey(monday) && s.date <= dateKey(addDays(monday, 6)) && s.status !== '취소').length, unit: '건', icon: MessageSquare, color: 'lavender', detail: `승인 대기 ${pending}건`, page: 'mentoring' },
      { label: '과제 제출', value: data.assignments.reduce((sum, a) => sum + a.submitted, 0), unit: '건', icon: ClipboardList, color: 'sky', detail: '저장된 제출 건수', page: 'assignments' },
    ].map(s => <button className="stat-card text-left" key={s.label} onClick={() => go(s.page)}><div className="stat-top"><span>{s.label}</span><span className={`stat-icon ${s.color}`}><s.icon size={18} /></span></div><div className="stat-value">{s.value}<span>{s.unit}</span><span className="stat-trend neutral"><ArrowUpRight size={14} /></span></div><p>{s.detail}</p></button>)}</section>
    <section className="dashboard-middle"><div className="panel participation"><CardHeading title="출결 현황" subtitle="등록된 출결 기록 기준 · 출석 및 공결 비율"><select aria-label="참여 현황 기간" className="select-control" value={period} onChange={e => setPeriod(e.target.value)}><option>이번 주</option><option>지난 주</option></select></CardHeading><div className="chart-summary"><strong>{attendance.length ? rate : '—'}<span>{attendance.length ? '%' : ''}</span></strong><Badge tone="neutral">{attendance.length}건</Badge><span>출석 · 공결 / 전체 기록</span></div><div className="chart" role="img" aria-label={`${period} 일별 출석률: ${values.join(', ')}%`}><div className="chart-scale"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div><div className="chart-plot"><div className="chart-grid"><i /><i /><i /><i /><i /></div><div className="bars">{values.map((v, i) => <div className="bar-column" key={i}><div className="bar-pair"><div className="bar primary" style={{ height: `${v}%` }} title={`${chartDays[i]} ${v}%`} /></div><span>{['월', '화', '수', '목', '금', '토', '일'][i]}</span></div>)}</div>{!attendance.length && <span className="chart-empty-label">해당 기간의 출결 기록이 없습니다.</span>}</div></div><div className="chart-footer"><span>{chartDays[0]} ~ {chartDays[6]}</span><button className="text-button" onClick={() => go('attendance')}>출결 관리 <ArrowRight size={13} /></button></div></div>
    <div className="panel schedule-panel"><CardHeading title="멘토링 일정"><button className="icon-button" aria-label="전체 멘토링 보기" onClick={() => go('mentoring')}><ArrowUpRight size={18} /></button></CardHeading><div className="calendar-heading"><strong>{days[0].getFullYear()}년 {days[0].getMonth() + 1}월</strong><div><button className="icon-button" aria-label="이전 주" onClick={() => { setWeekOffset(weekOffset - 1); setSelected(dateKey(addDays(days[0], -7))) }}><ChevronLeft size={15} /></button><button className="icon-button" aria-label="다음 주" onClick={() => { setWeekOffset(weekOffset + 1); setSelected(dateKey(addDays(days[0], 7))) }}><ChevronRight size={15} /></button></div></div><div className="week-strip">{days.map((day, i) => <button key={dateKey(day)} onClick={() => setSelected(dateKey(day))} className={selected === dateKey(day) ? 'selected' : ''} aria-label={`${day.getMonth() + 1}월 ${day.getDate()}일`} aria-pressed={selected === dateKey(day)}><span>{['월', '화', '수', '목', '금', '토', '일'][i]}</span><strong>{day.getDate()}</strong><i className={data.sessions.some(s => s.date === dateKey(day)) ? 'has-session' : ''} /></button>)}</div><div className="session-list">{sessions.slice(0, 3).map((s, i) => <button className="session-preview" key={s.id} onClick={() => go('mentoring')}><div className="session-time">{s.time}<span>{s.status}</span></div><div className={`session-line line-${i}`} /><div className="session-description"><strong>{s.title}</strong><span>{s.mentor} · {s.team}</span></div><ChevronRight size={14} /></button>)}{!sessions.length && <div className="calendar-empty"><CalendarDays size={24} /><p>등록된 일정이 없습니다.</p><button className="text-button" onClick={addSession}>일정 등록</button></div>}</div><button className="schedule-all" onClick={() => go('mentoring')}>전체 일정 <ArrowRight size={14} /></button></div></section>
    <section className="courses-section"><CardHeading title="과정 현황" subtitle="과정별 등록 인원 및 운영 상태"><button className="text-button" onClick={() => go('courses')}>전체 과정 <ArrowRight size={14} /></button></CardHeading><div className="courses-grid">{courses.slice(0, 3).map(c => <CourseCard course={c} key={c.id} onClick={() => selectCourse(c)} />)}</div>{courses.length === 0 && <Empty />}</section>
    <section className="bottom-grid"><div className="panel"><CardHeading title="진행 중인 과제"><button className="text-button" onClick={() => go('assignments')}>전체 보기 <ArrowRight size={14} /></button></CardHeading>{data.assignments.filter(a => a.status === '진행 중').slice(0, 3).map((a, i) => <button className="assignment-preview" key={a.id} onClick={() => go('assignments')}><span className={`assignment-icon ${i === 1 ? 'sage' : 'peach'}`}><ClipboardList size={19} /></span><span><strong>{a.title}</strong><small>{a.course} · {a.due} 마감</small></span><Badge tone="neutral">{a.submitted}건 제출</Badge><ChevronRight size={15} /></button>)}{!data.assignments.some(a => a.status === '진행 중') && <div className="calendar-empty">진행 중인 과제가 없습니다.</div>}</div><div className="bot-summary"><div className="flex items-center justify-between"><span className="bot-summary-icon"><Bot size={25} /></span><Badge tone={data.mode === 'api' ? 'green' : 'neutral'}>{data.mode === 'api' ? 'DB 연결됨' : '데모'}</Badge></div><h2>봇 데이터 연동</h2><p>멘토 · 예약 · 과제 · 제출 데이터<br />원격 실행 및 배포: 미연결</p><div className="bot-summary-stats"><span>멘토 <strong>{data.mentors.length}<small>명</small></strong></span><span>등록 환경 <strong>{data.servers.length}<small>개</small></strong></span><span>예약 <strong>{data.sessions.length}<small>건</small></strong></span></div><button onClick={() => go('bots')}>봇 · 서버 관리 <ArrowUpRight size={16} /></button></div></section>
  </>
}
