import AssignmentManagement from './AssignmentManagement'
import { ArrowUpRight, Bell, Bot, Check, CircleHelp, GraduationCap, MessageSquare, Power, Server, Terminal, Zap } from 'lucide-react'
import { Avatar, Badge, CardHeading, CourseCard, Empty } from './components'
import { type Course, type Workspace } from './data'

export type Change = (updater: (current: Workspace) => Workspace, message: string) => Promise<boolean>
export default function Management({ page, data, query, filter, setFilter, change, go, selectCourse, help }: { page: string; data: Workspace; query: string; filter: string; setFilter: (filter: string) => void; change: Change; go: (page: string) => void; selectCourse: (course: Course) => void; help: () => void }) {
  const matches = (text: string) => text.toLowerCase().includes(query.toLowerCase())
  const courses = data.courses.filter(c => matches(`${c.title} ${c.mentor}`) && (filter === '전체' || c.status === filter))
  const sessions = data.sessions.filter(s => matches(`${s.title} ${s.mentor} ${s.team}`) && (filter === '전체' || s.status === filter)).sort((a, b) => (a.date + a.time).localeCompare(b.date + b.time))
  const servers = data.servers.filter(s => matches(`${s.name} ${s.provider}`))
  if (page === 'courses') return <><div className="filter-row"><div className="tabs">{['전체', '진행 중', '모집 중', '종료'].map(f => <button className={filter === f ? 'selected' : ''} key={f} onClick={() => setFilter(f)}>{f}{f === '전체' && <span>{data.courses.length}</span>}</button>)}</div><span className="muted">총 {courses.length}개 과정</span></div><div className="courses-grid">{courses.map(c => <CourseCard key={c.id} course={c} onClick={() => selectCourse(c)} />)}</div>{!courses.length && <Empty />}</>
  if (page === 'mentoring') return <div className="panel"><CardHeading title="멘토링 예약 현황" subtitle={`승인을 기다리는 예약이 ${data.sessions.filter(s => s.status === '승인 대기').length}건 있어요.`}><select className="select-control" aria-label="예약 상태 필터" value={filter} onChange={e => setFilter(e.target.value)}>{['전체', '승인 대기', '예약 확정', '완료', '취소'].map(f => <option key={f}>{f}</option>)}</select></CardHeading><div className="table-scroll"><table><thead><tr><th>멘토링</th><th>담당 멘토</th><th>일정</th><th>상태</th><th>관리</th></tr></thead><tbody>{sessions.map(s => <tr key={s.id}><td><strong>{s.title}</strong><small>{s.team}</small></td><td><div className="person-cell"><Avatar name={s.mentor} small />{s.mentor}</div></td><td>{s.date}<small>{s.time} – 50분</small></td><td><Badge tone={s.status === '승인 대기' ? 'orange' : s.status === '완료' ? 'neutral' : 'green'}>{s.status}</Badge></td><td>{!['완료', '취소'].includes(s.status) ? <button className="button compact secondary" onClick={() => change(d => ({ ...d, sessions: d.sessions.map(row => row.id === s.id ? { ...row, status: s.status === '승인 대기' ? '예약 확정' : '완료' } : row) }), s.status === '승인 대기' ? '예약을 승인했습니다.' : '멘토링을 완료 처리했습니다.')}><Check size={14} />{s.status === '승인 대기' ? '승인' : '완료 처리'}</button> : <span className="muted">{s.status}</span>}{!['완료', '취소'].includes(s.status) && <button className="button compact secondary ml-2" onClick={() => change(d => ({ ...d, sessions: d.sessions.map(row => row.id === s.id ? { ...row, status: '취소' } : row) }), '예약을 취소했습니다.')}>취소</button>}</td></tr>)}</tbody></table></div>{!sessions.length && <Empty />}</div>
  if (page === 'assignments') return <AssignmentManagement data={data} query={query} change={change} />
  if (page === 'bots') return <><div className="inline-note"><Bot size={19} /><div><strong>서버 연결</strong><p>배포 환경 정보는 DB에 저장됩니다. 원격 봇 실행 및 배포 에이전트는 미연결 상태입니다.</p></div></div><div className="server-grid">{servers.map(s => <div className="panel server-card" key={s.id}><div className="flex justify-between items-center"><span className="server-icon"><Server size={24} /></span><Badge tone={s.status === '실행 중' ? 'green' : 'neutral'}><span className={s.status === '실행 중' ? 'online-dot' : 'offline-dot'} />{s.status}</Badge></div><h2>{s.name}</h2><p>{s.provider} <span>·</span> {s.region}</p><dl><div><dt>버전</dt><dd>{s.version}</dd></div><div><dt>연결 모드</dt><dd>{data.mode === 'api' ? '에이전트 미연결' : '데모'}</dd></div><div><dt>워크스페이스</dt><dd>{data.name}</dd></div></dl><div className="flex gap-2"><button disabled={data.mode === 'api'} className="button primary flex-1" onClick={() => change(d => ({ ...d, servers: d.servers.map(row => row.id === s.id ? { ...row, status: s.status === '실행 중' ? '중지됨' : '실행 중' } : row), logs: [...d.logs, { id: crypto.randomUUID(), time: new Date().toLocaleTimeString('ko-KR', { hour12: false }), text: `${s.name} 데모 ${s.status === '실행 중' ? '중지' : '배포 실행'} 완료` }] }), `데모 봇을 ${s.status === '실행 중' ? '중지' : '실행'}했습니다.`)}>{s.status === '실행 중' ? <Power size={16} /> : <Zap size={16} />}{data.mode === 'api' ? '실행 제어 미연결' : s.status === '실행 중' ? '봇 중지' : '데모 배포'}</button><button className="button secondary" onClick={() => go('logs')}><Terminal size={16} /> 로그</button></div></div>)}</div>{!servers.length && <Empty />}<div className="panel modules-panel"><CardHeading title="학습 운영 모듈" subtitle="모듈 실행 설정은 봇의 환경변수에서 관리합니다. 웹 제어는 미연결 상태입니다." /><div className="module-grid">{[{ key: 'reminders' as const, title: '멘토링 리마인더', description: '예약된 멘토링 시간을 안내합니다.', icon: Bell }, { key: 'onboarding' as const, title: '수강생 온보딩', description: '수강생 등록 및 역할 설정', icon: GraduationCap }, { key: 'qa' as const, title: 'Q&A 알림', description: '답변을 기다리는 질문을 알려줍니다.', icon: MessageSquare }].map(m => <div className="module" key={m.key}><m.icon size={21} /><div><strong>{m.title}</strong><p>{m.description}</p></div><button disabled={data.mode === 'api'} role="switch" aria-checked={data[m.key]} aria-label={m.title} className={`toggle ${data[m.key] ? 'on' : ''}`} onClick={() => change(d => ({ ...d, [m.key]: !d[m.key] }), '데모 모듈 설정을 변경했습니다.')}><span /></button></div>)}</div></div></>
  if (page === 'logs') return <div className="panel"><CardHeading title="워크스페이스 활동" subtitle="등록·수정 작업의 변경 전후 이력을 저장합니다."><Badge tone="neutral">{data.logs.length}개 이벤트</Badge></CardHeading><div className="log-console">{data.logs.filter(l => matches(l.text)).toReversed().map(l => <div key={l.id}><time>{l.time}</time><span>INFO</span><div><p>{l.text}</p>{l.before && <details className="audit-details"><summary>변경 내용</summary><pre>{JSON.stringify({ before: JSON.parse(l.before), after: JSON.parse(l.after || 'null') }, null, 2)}</pre></details>}</div></div>)}{!data.logs.some(l => matches(l.text)) && <p className="p-5">검색된 활동이 없습니다.</p>}</div></div>
  return <div className="settings-grid"><form className="panel settings-form" onSubmit={e => { e.preventDefault(); const fields = new FormData(e.currentTarget); const name = String(fields.get('name') || '').trim(); if (name) change(d => ({ ...d, name }), '워크스페이스 설정을 저장했습니다.') }}><CardHeading title="기본 정보" subtitle="워크스페이스의 이름과 운영 정보를 관리합니다." /><label>워크스페이스 이름<input name="name" key={data.name} defaultValue={data.name} required maxLength={40} pattern=".*\S.*" /></label><label>데이터 저장<input value={data.mode === 'api' ? '서버에 저장' : '데모 · 이 브라우저에 저장'} readOnly /></label><button className="button primary" type="submit"><Check size={16} /> 변경 사항 저장</button></form><div className="panel settings-info"><CircleHelp size={27} /><h2>연결과 운영 안내</h2><p>Discord 빠른 설정에서 서버를 연결하고 앱 초대와 LMS 인증을 완료하세요.</p><p>학생 계정은 학생 계정 발급에서 준비하세요. 비밀번호 재발급이나 계정 삭제는 총관리자에게 요청하세요.</p><p>출결·과제·공지의 저장과 Discord 발송 상태는 각 관리 화면에서 확인할 수 있습니다.</p><button className="text-button" onClick={help}>운영 가이드 보기 <ArrowUpRight size={14} /></button></div></div>
}
