import { useState, type FormEvent } from 'react'
import { ArrowDownToLine, ExternalLink, FileBox, Pencil, Plus } from 'lucide-react'
import { Badge, CardHeading, Empty, ModalShell } from './components'
import type { RecordData, Workspace } from './data'
import type { Change } from './Management'
import NoticeDelivery from './NoticeDelivery'
import TeamOperations from './TeamOperations'
